In [ ]:
%%capture
!pip install pymupdf pandas python-dotenv openai tqdm
!pip install -U google-api-python-client google-auth-httplib2 google-auth-oauthlib
!pip install easyocr pdf2image pypdf
!pip install gdown
!apt-get install -y poppler-utils

In [ ]:
import gdown
import os

# 1. Google Drive link to download invoices
drive_url = "Your Drive URL"

# 2. Define the local folder name
output_folder = "invoices"

# 3. Create the folder if it doesn't already exist
if not os.path.exists(output_folder):
    os.makedirs(output_folder)
    print(f"Created directory: {output_folder}")

# 4. Download the contents into the 'invoices'
gdown.download_folder(drive_url, output=output_folder, quiet=False, use_cookies=False)

Created directory: invoices

Retrieving folder contents

Processing file 1L6i3ZD3ARcmm8LjhFl_1qqksSeL3ifng Copy of ARPFIINVOEBTCHLASER (1).pdf
Processing file 1-ZnLgZ1nBrgIgT9oFyNdykquEgZZLukR Copy of ARPFIINVOEBTCHLASER (2).pdf
Processing file 1ZmRdVXqvb-tse4pc8MUKfTla5WZnAcCL Copy of ARPFIINVOEBTCHLASER (3).pdf
Processing file 14Jp8599xbUqOCGbKnVQPOigTMm0L1TBR Copy of ARPFIINVOEBTCHLASER (4).pdf
Processing file 1TwNhSTt6HjtWkr07tLWTWbvL-1QQm8eY Copy of ARPFIINVOEBTCHLASER (5).pdf
Processing file 1BntRm9_iLlUBRMXcNkWgfenIi0ZwkuTa Copy of ARPFIINVOEBTCHLASER (6).pdf
Processing file 1XN_4bokyPtuXCOKua9chg6IDuk7uqnQx Copy of ARPFIINVOEBTCHLASER (7).pdf
Processing file 1-GduiZQVYwTvCvce67bqts2YEzBwb-FH Copy of ARPFIINVOEBTCHLASER (8).pdf
Processing file 1inbal8MhzQ3e2qgUQvaIHJjvPLdbMoum Copy of ARPFIINVOEBTCHLASER (9).pdf
Processing file 1GC21wGevl169oMZG5E3H8KRTQ0SP39o5 Copy of ARPFIINVOEBTCHLASER (10).pdf
Processing file 1ZxgDDwtf_JwGRdTUEgY5A5gI6v-eq44_ Copy of ARPFIINVOEBTCHLASER (11).pdf
Processing file 1Z1MhINKP0XKPsfeMiQTWclXBnPjYCgOS Copy of ARPFIINVOEBTCHLASER (12).pdf
Processing file 1jdS3vjvWU0w62w3PP5q71yuG84MMl0Yk Copy of ARPFIINVOEBTCHLASER (13).pdf
Processing file 1GqhsQqnJVVb_Gvj86NAai_FxKWhJVbW3 Copy of ARPFIINVOEBTCHLASER (14).pdf
Processing file 1NuUcFGqHFM8DI7T6rEVvUm-MXd-Z7ubJ Copy of ARPFIINVOEBTCHLASER.pdf
Processing file 1GzGhUZoBK4LZwihS0FmG5sMsHJhwSFxF Copy of Inv_20065629_from_Franks_Quality_Produce_18417572_22492.pdf
Processing file 1XbIQzwUrFMr50C12SkT7XhovVPtk9yvT Copy of Inv_20066901_from_Franks_Quality_Produce_18471648_18416.pdf
Processing file 17CQ5rMCh5P1NvsK1Qn1bY6Hl2HZtMHpS Copy of Inv_20068140_from_Franks_Quality_Produce_18529019_11828.pdf
Processing file 1eUeSIRQTY9yi8pIQECSvolZGGfZcPdPj Copy of Inv_20068978_from_Franks_Quality_Produce_18559799_11828.pdf
Processing file 1DxPCYsl27p4rV8ArcyE5Xcxx7LMB74WW Copy of Inv_20071084_from_Franks_Quality_Produce_18665028_7884.pdf
Processing file 1-gfkMfK8Fh9pYqQeA4s97zsCIcssqJac Copy of Inv_20072265_from_Franks_Quality_Produce_18697771_15688.pdf
Processing file 1iMmajISklDyiVbmW10Dcwpxu86kPpBFq Copy of Inv_20072898_from_Franks_Quality_Produce_18731344_15688.pdf
Processing file 1W-PSy3p9xakWObf_mlHUTjxVp--x0T5z Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408 (1).pdf
Processing file 1jFe4IdZhyDDIRWCGdzYw9CuJarj4Fv_H Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408.pdf
Processing file 1jm1TQNOCm_sunyziyTt-RLdz7_a2kQjY Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952 (1).pdf
Processing file 1_RzGpU7pNPWMod3usZnOFRjTpAxvGKIV Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952.pdf
Processing file 1FD3dR6wozZTTuqilwBZZ2YAUoh2rqVw2 Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748 (1).pdf
Processing file 1pgS2CG5re5PqSA-hh5YOvDntv9FGqMto Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748.pdf
Processing file 1DhMbHD2VGlSy567mewL1mBHvkQtNv7KX Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596 (1).pdf
Processing file 1NGcnqS5zAnMPNUdTLQ7ZsDVpMG7KLVf6 Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596.pdf
Processing file 1S-fzpa0nfkZlpL3Ly6CbPRSADrKh8a8E Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132 (1).pdf
Processing file 1VDH6Vmn_Q91o9AEBZhorhK5jggfu8PIY Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132.pdf

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1L6i3ZD3ARcmm8LjhFl_1qqksSeL3ifng
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (1).pdf
100%|██████████| 39.4k/39.4k [00:00<00:00, 68.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-ZnLgZ1nBrgIgT9oFyNdykquEgZZLukR
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (2).pdf
100%|██████████| 39.3k/39.3k [00:00<00:00, 65.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ZmRdVXqvb-tse4pc8MUKfTla5WZnAcCL
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (3).pdf
100%|██████████| 39.3k/39.3k [00:00<00:00, 49.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=14Jp8599xbUqOCGbKnVQPOigTMm0L1TBR
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (4).pdf
100%|██████████| 46.5k/46.5k [00:00<00:00, 72.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1TwNhSTt6HjtWkr07tLWTWbvL-1QQm8eY
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (5).pdf
100%|██████████| 39.2k/39.2k [00:00<00:00, 38.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1BntRm9_iLlUBRMXcNkWgfenIi0ZwkuTa
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (6).pdf
100%|██████████| 41.9k/41.9k [00:00<00:00, 34.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1XN_4bokyPtuXCOKua9chg6IDuk7uqnQx
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (7).pdf
100%|██████████| 39.1k/39.1k [00:00<00:00, 62.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-GduiZQVYwTvCvce67bqts2YEzBwb-FH
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (8).pdf
100%|██████████| 46.6k/46.6k [00:00<00:00, 47.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1inbal8MhzQ3e2qgUQvaIHJjvPLdbMoum
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (9).pdf
100%|██████████| 46.6k/46.6k [00:00<00:00, 28.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1GC21wGevl169oMZG5E3H8KRTQ0SP39o5
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (10).pdf
100%|██████████| 46.7k/46.7k [00:00<00:00, 69.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ZxgDDwtf_JwGRdTUEgY5A5gI6v-eq44_
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (11).pdf
100%|██████████| 46.7k/46.7k [00:00<00:00, 67.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Z1MhINKP0XKPsfeMiQTWclXBnPjYCgOS
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (12).pdf
100%|██████████| 39.2k/39.2k [00:00<00:00, 68.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1jdS3vjvWU0w62w3PP5q71yuG84MMl0Yk
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (13).pdf
100%|██████████| 39.3k/39.3k [00:00<00:00, 36.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1GqhsQqnJVVb_Gvj86NAai_FxKWhJVbW3
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (14).pdf
100%|██████████| 39.0k/39.0k [00:00<00:00, 23.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1NuUcFGqHFM8DI7T6rEVvUm-MXd-Z7ubJ
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER.pdf
100%|██████████| 39.1k/39.1k [00:00<00:00, 62.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1GzGhUZoBK4LZwihS0FmG5sMsHJhwSFxF
To: /content/invoices/Copy of Inv_20065629_from_Franks_Quality_Produce_18417572_22492.pdf
100%|██████████| 73.4k/73.4k [00:00<00:00, 51.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1XbIQzwUrFMr50C12SkT7XhovVPtk9yvT
To: /content/invoices/Copy of Inv_20066901_from_Franks_Quality_Produce_18471648_18416.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 50.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=17CQ5rMCh5P1NvsK1Qn1bY6Hl2HZtMHpS
To: /content/invoices/Copy of Inv_20068140_from_Franks_Quality_Produce_18529019_11828.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 43.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1eUeSIRQTY9yi8pIQECSvolZGGfZcPdPj
To: /content/invoices/Copy of Inv_20068978_from_Franks_Quality_Produce_18559799_11828.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 88.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1DxPCYsl27p4rV8ArcyE5Xcxx7LMB74WW
To: /content/invoices/Copy of Inv_20071084_from_Franks_Quality_Produce_18665028_7884.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 85.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-gfkMfK8Fh9pYqQeA4s97zsCIcssqJac
To: /content/invoices/Copy of Inv_20072265_from_Franks_Quality_Produce_18697771_15688.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 53.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1iMmajISklDyiVbmW10Dcwpxu86kPpBFq
To: /content/invoices/Copy of Inv_20072898_from_Franks_Quality_Produce_18731344_15688.pdf
100%|██████████| 73.4k/73.4k [00:00<00:00, 12.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1W-PSy3p9xakWObf_mlHUTjxVp--x0T5z
To: /content/invoices/Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408 (1).pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 43.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1jFe4IdZhyDDIRWCGdzYw9CuJarj4Fv_H
To: /content/invoices/Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 74.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1jm1TQNOCm_sunyziyTt-RLdz7_a2kQjY
To: /content/invoices/Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952 (1).pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 53.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1_RzGpU7pNPWMod3usZnOFRjTpAxvGKIV
To: /content/invoices/Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 85.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1FD3dR6wozZTTuqilwBZZ2YAUoh2rqVw2
To: /content/invoices/Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748 (1).pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 81.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1pgS2CG5re5PqSA-hh5YOvDntv9FGqMto
To: /content/invoices/Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 86.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1DhMbHD2VGlSy567mewL1mBHvkQtNv7KX
To: /content/invoices/Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596 (1).pdf
100%|██████████| 73.5k/73.5k [00:00<00:00, 76.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1NGcnqS5zAnMPNUdTLQ7ZsDVpMG7KLVf6
To: /content/invoices/Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596.pdf
100%|██████████| 73.5k/73.5k [00:00<00:00, 74.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1S-fzpa0nfkZlpL3Ly6CbPRSADrKh8a8E
To: /content/invoices/Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132 (1).pdf
100%|██████████| 73.1k/73.1k [00:00<00:00, 69.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1VDH6Vmn_Q91o9AEBZhorhK5jggfu8PIY
To: /content/invoices/Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132.pdf
100%|██████████| 73.1k/73.1k [00:00<00:00, 30.6MB/s]
Download completed

['invoices/Copy of ARPFIINVOEBTCHLASER (1).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (2).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (3).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (4).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (5).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (6).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (7).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (8).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (9).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (10).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (11).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (12).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (13).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (14).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER.pdf',
 'invoices/Copy of Inv_20065629_from_Franks_Quality_Produce_18417572_22492.pdf',
 'invoices/Copy of Inv_20066901_from_Franks_Quality_Produce_18471648_18416.pdf',
 'invoices/Copy of Inv_20068140_from_Franks_Quality_Produce_18529019_11828.pdf',
 'invoices/Copy of Inv_20068978_from_Franks_Quality_Produce_18559799_11828.pdf',
 'invoices/Copy of Inv_20071084_from_Franks_Quality_Produce_18665028_7884.pdf',
 'invoices/Copy of Inv_20072265_from_Franks_Quality_Produce_18697771_15688.pdf',
 'invoices/Copy of Inv_20072898_from_Franks_Quality_Produce_18731344_15688.pdf',
 'invoices/Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408 (1).pdf',
 'invoices/Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408.pdf',
 'invoices/Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952 (1).pdf',
 'invoices/Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952.pdf',
 'invoices/Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748 (1).pdf',
 'invoices/Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748.pdf',
 'invoices/Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596 (1).pdf',
 'invoices/Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596.pdf',
 'invoices/Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132 (1).pdf',
 'invoices/Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132.pdf']

In [ ]:
import easyocr
import os
import json
import openai
import pypdf
from PIL import Image
from pdf2image import convert_from_path
from google.colab import userdata
from pydantic import BaseModel
from typing import List

In [ ]:
# 2. Define Data Schema
class LineItem(BaseModel):
    description: str
    quantity: float
    unit_price: float
    line_total: float

class InvoiceData(BaseModel):
    invoice_number: str
    date: str
    vendor: str
    total_amount: float
    line_items: List[LineItem]

# 3. Setup OpenRouter Client
api_key = userdata.get('OPENROUTER_API_KEY')
client = openai.OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key,
)

reader = easyocr.Reader(['en'])

WARNING:easyocr.easyocr:Downloading detection model, please wait. This may take several minutes depending upon your network connection.

Progress: |██████████████████████████████████████████████████| 100.0% Complete

WARNING:easyocr.easyocr:Downloading recognition model, please wait. This may take several minutes depending upon your network connection.

Progress: |██████████████████████████████████████████████████| 100.0% Complete

In [ ]:
import fitz  # PyMuPDF
import os

input_folder = "/content/invoices"
output_folder = "Invoices_images"

if not os.path.exists(output_folder):
    os.makedirs(output_folder)

for filename in os.listdir(input_folder):
    if filename.lower().endswith(".pdf"):
        pdf_path = os.path.join(input_folder, filename)

        # Open the PDF
        doc = fitz.open(pdf_path)

        for i, page in enumerate(doc):
            # Increase resolution (2.0 = 2x zoom/DPI)
            # This makes the OCR much more accurate
            zoom = 2.0
            mat = fitz.Matrix(zoom, zoom)
            pix = page.get_pixmap(matrix=mat)

            # Define image name
            base_name = os.path.splitext(filename)[0]
            image_path = os.path.join(output_folder, f"{base_name}_pg{i+1}.png")

            # Save the image
            pix.save(image_path)

        doc.close()
        print(f"Converted: {filename}")

print("\n✅ All PDFs converted to images in the /invoice_images folder.")

Converted: Copy of ARPFIINVOEBTCHLASER (1).pdf
Converted: Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952 (1).pdf
Converted: Copy of ARPFIINVOEBTCHLASER (14).pdf
Converted: Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408 (1).pdf
Converted: Copy of ARPFIINVOEBTCHLASER (4).pdf
Converted: Copy of Inv_20068978_from_Franks_Quality_Produce_18559799_11828.pdf
Converted: Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952.pdf
Converted: Copy of ARPFIINVOEBTCHLASER (9).pdf
Converted: Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408.pdf
Converted: Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596 (1).pdf
Converted: Copy of Inv_20068140_from_Franks_Quality_Produce_18529019_11828.pdf
Converted: Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748 (1).pdf
Converted: Copy of ARPFIINVOEBTCHLASER (5).pdf
Converted: Copy of ARPFIINVOEBTCHLASER (10).pdf
Converted: Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596.pdf
Converted: Copy of ARPFIINVOEBTCHLASER (8).pdf
Converted: Copy of ARPFIINVOEBTCHLASER (13).pdf
Converted: Copy of ARPFIINVOEBTCHLASER (7).pdf
Converted: Copy of Inv_20065629_from_Franks_Quality_Produce_18417572_22492.pdf
Converted: Copy of Inv_20066901_from_Franks_Quality_Produce_18471648_18416.pdf
Converted: Copy of Inv_20072898_from_Franks_Quality_Produce_18731344_15688.pdf
Converted: Copy of Inv_20072265_from_Franks_Quality_Produce_18697771_15688.pdf
Converted: Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132.pdf
Converted: Copy of ARPFIINVOEBTCHLASER (12).pdf
Converted: Copy of ARPFIINVOEBTCHLASER.pdf
Converted: Copy of Inv_20071084_from_Franks_Quality_Produce_18665028_7884.pdf
Converted: Copy of ARPFIINVOEBTCHLASER (3).pdf
Converted: Copy of ARPFIINVOEBTCHLASER (2).pdf
Converted: Copy of ARPFIINVOEBTCHLASER (6).pdf
Converted: Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132 (1).pdf
Converted: Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748.pdf
Converted: Copy of ARPFIINVOEBTCHLASER (11).pdf

✅ All PDFs converted to images in the /invoice_images folder.

In [ ]:
import os
import json
import gc
import easyocr
import numpy as np

from PIL import Image
from tqdm import tqdm
from typing import List
from pydantic import BaseModel
from openai import OpenAI
from google.colab import userdata

In [ ]:
api_key = userdata.get("OPENROUTER_API_KEY")

client = OpenAI(
    base_url="https://openrouter.ai/api/v1",
    api_key=api_key,
)

In [ ]:
class LineItem(BaseModel):
    description: str
    quantity: float
    unit_price: float
    line_total: float

class InvoiceData(BaseModel):
    invoice_number: str
    date: str
    vendor: str
    total_amount: float
    line_items: List[LineItem]

In [ ]:
reader = easyocr.Reader(['en'], gpu=True)

In [ ]:
def extract_text_from_image(image_path):

    img = Image.open(image_path).convert("RGB")

    img.thumbnail((1500, 1500))   # 🔥 prevents RAM crash

    img_np = np.array(img)

    results = reader.readtext(img_np, detail=0, paragraph=True)

    del img, img_np
    gc.collect()

    return "\n".join(results)

In [ ]:
def process_invoice_ai(text):

    text = text[:6000]   # 🔥 reduce token cost & memory

    prompt = f"""
Extract invoice data into STRICT JSON.

Return ONLY valid JSON.

Schema:
{InvoiceData.model_json_schema()}

TEXT:
{text}
"""

    response = client.chat.completions.create(
        model="stepfun/step-3.5-flash:free",
        messages=[{"role": "user", "content": prompt}]
    )

    return json.loads(response.choices[0].message.content)

In [ ]:
!unzip invoices_images.zip

unzip:  cannot find or open invoices_images.zip, invoices_images.zip.zip or invoices_images.zip.ZIP.

In [ ]:
import os

print("Folder exists:", os.path.exists(input_folder))
print("Files:", os.listdir(input_folder))

Folder exists: True
Files: ['Copy of ARPFIINVOEBTCHLASER (2)_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (10)_pg4.png', 'Copy of ARPFIINVOEBTCHLASER (11)_pg1.png', 'Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (3)_pg1.png', 'Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (7)_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (10)_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (8)_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (11)_pg4.png', 'Copy of ARPFIINVOEBTCHLASER (4)_pg1.png', 'Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748 (1)_pg1.png', 'Copy of Inv_20066901_from_Franks_Quality_Produce_18471648_18416_pg1.png', 'Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (12)_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (9)_pg3.png', 'Copy of ARPFIINVOEBTCHLASER (14)_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (9)_pg2.png', 'Copy of ARPFIINVOEBTCHLASER_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (8)_pg2.png', 'Copy of ARPFIINVOEBTCHLASER (8)_pg4.png', 'Copy of ARPFIINVOEBTCHLASER (9)_pg1.png', 'Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952 (1)_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (6)_pg1.png', 'Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596 (1)_pg1.png', 'Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408_pg1.png', 'Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (4)_pg2.png', 'Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132 (1)_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (13)_pg1.png', 'Copy of Inv_20065629_from_Franks_Quality_Produce_18417572_22492_pg1.png', 'Copy of Inv_20068140_from_Franks_Quality_Produce_18529019_11828_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (10)_pg3.png', 'Copy of ARPFIINVOEBTCHLASER (11)_pg3.png', 'Copy of ARPFIINVOEBTCHLASER (4)_pg4.png', 'Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408 (1)_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (8)_pg3.png', 'Copy of ARPFIINVOEBTCHLASER (1)_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (6)_pg2.png', 'Copy of Inv_20072265_from_Franks_Quality_Produce_18697771_15688_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (4)_pg3.png', 'Copy of ARPFIINVOEBTCHLASER (5)_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (11)_pg2.png', 'Copy of Inv_20072898_from_Franks_Quality_Produce_18731344_15688_pg1.png', 'Copy of ARPFIINVOEBTCHLASER (10)_pg2.png', 'Copy of ARPFIINVOEBTCHLASER (9)_pg4.png', 'Copy of Inv_20068978_from_Franks_Quality_Produce_18559799_11828_pg1.png', 'Copy of Inv_20071084_from_Franks_Quality_Produce_18665028_7884_pg1.png']

In [ ]:
input_folder = "/content/Invoices_images"
output_folder = "/content/output_json"

os.makedirs(output_folder, exist_ok=True)

In [ ]:
all_results = []

image_files = [
    f for f in os.listdir(input_folder)
    if f.lower().endswith((".png", ".jpg", ".jpeg", ".webp"))
]

for file in tqdm(image_files):

    file_path = os.path.join(input_folder, file)

    print(f"\nProcessing → {file}")

    try:
        raw_text = extract_text_from_image(file_path)

        json_data = process_invoice_ai(raw_text)

        validated = InvoiceData(**json_data)

        all_results.append(validated.dict())

        with open(f"{output_folder}/{file}.json", "w") as f:
            json.dump(validated.dict(), f, indent=2)

    except Exception as e:
        print(f"❌ Failed → {file} → {e}")

    gc.collect()

  0%|          | 0/48 [00:00<?, ?it/s]

Processing → Copy of ARPFIINVOEBTCHLASER (2)_pg1.png

/tmp/ipython-input-232/1327713.py:21: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
  all_results.append(validated.dict())
/tmp/ipython-input-232/1327713.py:24: PydanticDeprecatedSince20: The `dict` method is deprecated; use `model_dump` instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.12/migration/
  json.dump(validated.dict(), f, indent=2)
  2%|▏         | 1/48 [02:45<2:09:33, 165.40s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (10)_pg4.png

  4%|▍         | 2/48 [03:28<1:11:27, 93.21s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (11)_pg1.png

  6%|▋         | 3/48 [08:03<2:12:11, 176.25s/it]

Processing → Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132_pg1.png

  8%|▊         | 4/48 [08:51<1:32:13, 125.76s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (3)_pg1.png

 10%|█         | 5/48 [11:08<1:33:06, 129.92s/it]

Processing → Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596_pg1.png

 12%|█▎        | 6/48 [13:21<1:31:31, 130.75s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (7)_pg1.png

 15%|█▍        | 7/48 [16:26<1:41:35, 148.67s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (10)_pg1.png

 17%|█▋        | 8/48 [18:38<1:35:31, 143.30s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (8)_pg1.png

 19%|█▉        | 9/48 [20:53<1:31:21, 140.54s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (11)_pg4.png

 21%|██        | 10/48 [21:27<1:08:13, 107.71s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (4)_pg1.png

 23%|██▎       | 11/48 [23:23<1:07:59, 110.25s/it]

Processing → Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748 (1)_pg1.png

 25%|██▌       | 12/48 [24:54<1:02:46, 104.62s/it]

Processing → Copy of Inv_20066901_from_Franks_Quality_Produce_18471648_18416_pg1.png

 27%|██▋       | 13/48 [25:58<53:42, 92.07s/it]

Processing → Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952_pg1.png

 29%|██▉       | 14/48 [27:26<51:30, 90.90s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (12)_pg1.png

 31%|███▏      | 15/48 [30:11<1:02:16, 113.21s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (9)_pg3.png

 33%|███▎      | 16/48 [31:09<51:33, 96.67s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (14)_pg1.png

 35%|███▌      | 17/48 [33:26<56:16, 108.91s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (9)_pg2.png

 38%|███▊      | 18/48 [34:40<49:09, 98.30s/it]

Processing → Copy of ARPFIINVOEBTCHLASER_pg1.png

 40%|███▉      | 19/48 [35:51<43:30, 90.03s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (8)_pg2.png

 42%|████▏     | 20/48 [38:10<48:56, 104.88s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (8)_pg4.png

 44%|████▍     | 21/48 [39:04<40:18, 89.56s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (9)_pg1.png

 46%|████▌     | 22/48 [41:45<48:03, 110.92s/it]

Processing → Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952 (1)_pg1.png

 48%|████▊     | 23/48 [43:18<43:57, 105.48s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (6)_pg1.png

 50%|█████     | 24/48 [45:14<43:26, 108.61s/it]

Processing → Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596 (1)_pg1.png

 52%|█████▏    | 25/48 [47:30<44:50, 116.96s/it]

Processing → Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408_pg1.png

 54%|█████▍    | 26/48 [48:21<35:35, 97.08s/it]

Processing → Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748_pg1.png

 56%|█████▋    | 27/48 [49:57<33:54, 96.89s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (4)_pg2.png

 58%|█████▊    | 28/48 [51:02<29:06, 87.32s/it]

Processing → Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132 (1)_pg1.png

 60%|██████    | 29/48 [51:42<23:07, 73.04s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (13)_pg1.png

 62%|██████▎   | 30/48 [55:11<34:08, 113.80s/it]

Processing → Copy of Inv_20065629_from_Franks_Quality_Produce_18417572_22492_pg1.png

 65%|██████▍   | 31/48 [56:50<31:02, 109.57s/it]

Processing → Copy of Inv_20068140_from_Franks_Quality_Produce_18529019_11828_pg1.png

 67%|██████▋   | 32/48 [57:53<25:27, 95.48s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (10)_pg3.png

 69%|██████▉   | 33/48 [58:52<21:05, 84.38s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (11)_pg3.png

 71%|███████   | 34/48 [1:00:25<20:20, 87.21s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (4)_pg4.png

 73%|███████▎  | 35/48 [1:01:20<16:45, 77.31s/it]

Processing → Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408 (1)_pg1.png

 75%|███████▌  | 36/48 [1:02:25<14:43, 73.63s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (8)_pg3.png

 77%|███████▋  | 37/48 [1:03:24<12:44, 69.50s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (1)_pg1.png

 79%|███████▉  | 38/48 [1:05:49<15:20, 92.06s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (6)_pg2.png

 81%|████████▏ | 39/48 [1:06:23<11:12, 74.67s/it]

Processing → Copy of Inv_20072265_from_Franks_Quality_Produce_18697771_15688_pg1.png

 83%|████████▎ | 40/48 [1:08:18<11:33, 86.65s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (4)_pg3.png

 85%|████████▌ | 41/48 [1:08:58<08:29, 72.83s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (5)_pg1.png

 88%|████████▊ | 42/48 [1:12:04<10:39, 106.50s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (11)_pg2.png

 90%|████████▉ | 43/48 [1:12:46<07:16, 87.31s/it]

Processing → Copy of Inv_20072898_from_Franks_Quality_Produce_18731344_15688_pg1.png

 92%|█████████▏| 44/48 [1:14:21<05:58, 89.67s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (10)_pg2.png

 94%|█████████▍| 45/48 [1:16:07<04:43, 94.39s/it]

Processing → Copy of ARPFIINVOEBTCHLASER (9)_pg4.png

 96%|█████████▌| 46/48 [1:16:55<02:41, 80.53s/it]

Processing → Copy of Inv_20068978_from_Franks_Quality_Produce_18559799_11828_pg1.png

 98%|█████████▊| 47/48 [1:18:39<01:27, 87.77s/it]

Processing → Copy of Inv_20071084_from_Franks_Quality_Produce_18665028_7884_pg1.png

100%|██████████| 48/48 [1:19:53<00:00, 99.87s/it]

In [ ]:
with open("/content/all_invoices.json", "w") as f:
    json.dump(all_results, f, indent=2)

In [ ]:
all_results

[{'invoice_number': '378793',
  'date': '07/29/2025',
  'vendor': 'Pacific Food Importers Inc.',
  'total_amount': 754.89,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT 50 LB',
    'quantity': 10.0001,
    'unit_price': 24.063,
    'line_total': 240.0},
   {'description': 'ONION MINCED MARCA CROC 4 * 4 .5 LB',
    'quantity': 1.0,
    'unit_price': 113.333,
    'line_total': 113.33},
   {'description': 'SESAME SEEDS MHITE+ MARCA CROC 4 LB',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'SALT KOSHER COARSE DIAMOND CR 3 LB',
    'quantity': 2.0,
    'unit_price': 75.076,
    'line_total': 150.15},
   {'description': 'GLOVE NITRILE XL 10 100 ct',
    'quantity': 1.0,
    'unit_price': 36.25,
    'line_total': 36.25},
   {'description': 'YEAST INSTANT RED LBL SAF 20',
    'quantity': 1.0,
    'unit_price': 130.0,
    'line_total': 130.0}]},
 {'invoice_number': '376172',
  'date': '06/05/2025',
  'vendor': 'Pacific Flood mporters INc',
  'total_amount': 133.42,
  'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20.000 LB',
    'quantity': 1.0,
    'unit_price': 133.418,
    'line_total': 133.0}]},
 {'invoice_number': '375991',
  'date': '06/03/2025',
  'vendor': 'Pacific Flood Importers Inc',
  'total_amount': 491.83,
  'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'FLOUR A/P UNBLEACHED GRAINCRAFT',
    'quantity': 1.0,
    'unit_price': 21.0,
    'line_total': 21.0},
   {'description': 'FLOUR MEDIUM RYE',
    'quantity': 1.0,
    'unit_price': 42.8,
    'line_total': 42.8},
   {'description': 'FLOUR MEDIUM RYE',
    'quantity': 1.0,
    'unit_price': 42.8,
    'line_total': 42.8},
   {'description': 'CORNMEAL YELLOH FINE** * 25 LB',
    'quantity': 1.0,
    'unit_price': 25.86,
    'line_total': 25.86},
   {'description': 'SALT KOSHER COARSE DIAMOND CR',
    'quantity': 9.0,
    'unit_price': 7.962,
    'line_total': 71.66},
   {'description': 'GLOVE NITRILE LARGE 10 X 100',
    'quantity': 1.0,
    'unit_price': 29.77,
    'line_total': 29.77},
   {'description': 'EGGS LIQUID PAPETTIS',
    'quantity': 1.0,
    'unit_price': 50.18,
    'line_total': 50.18}]},
 {'invoice_number': '20078834',
  'date': '8/14/2025',
  'vendor': "Frank's QQuality Produce",
  'total_amount': 53.35,
  'line_items': [{'description': 'ONION, GREEN',
    'quantity': 2.0,
    'unit_price': 10.0,
    'line_total': 20.0},
   {'description': 'CUCUMBER, XFANCY LG',
    'quantity': 15.0,
    'unit_price': 0.99,
    'line_total': 14.85},
   {'description': 'HERBS, DILL BABY',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '378483',
  'date': '07/22/2025',
  'vendor': 'Pacific Flood mporters INc',
  'total_amount': 576.63,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT LB',
    'quantity': 10.0001,
    'unit_price': 24.063,
    'line_total': 240.0},
   {'description': 'MALT POWDER DIASTATIC+ RED STAR JALAPENO SLICED #10 SAVOR LB',
    'quantity': 1.0,
    'unit_price': 116.848,
    'line_total': 116.85},
   {'description': '45.000 LB',
    'quantity': 1.0,
    'unit_price': 329.0,
    'line_total': 51.33},
   {'description': 'GLOVE NITRILE MEDIUM',
    'quantity': 1.0,
    'unit_price': 29.78,
    'line_total': 29.78},
   {'description': 'EGGS LIQUID PAPETTIS X 20 LB',
    'quantity': 1.0,
    'unit_price': 95.225,
    'line_total': 95.23}]},
 {'invoice_number': '20077622',
  'date': '8/6/2025',
  'vendor': "Frank's QQuality Produce",
  'total_amount': 79.11,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 12.0,
    'unit_price': 1.99,
    'line_total': 23.88},
   {'description': 'HERBS, DILL BABY HERBS, PARSLEY, ITALIAN',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'CUCUMBER, XFANCY',
    'quantity': 6.0,
    'unit_price': 0.99,
    'line_total': 5.94},
   {'description': 'ONION, GREEN',
    'quantity': 14.0,
    'unit_price': 0.99,
    'line_total': 13.86},
   {'description': 'ONION, ITALIAN RED',
    'quantity': 1.0,
    'unit_price': 10.0,
    'line_total': 10.0},
   {'description': 'BAG ONION, ITALIAN RED',
    'quantity': 7.0,
    'unit_price': 0.99,
    'line_total': 6.93},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5},
   {'description': 'Sales Tax',
    'quantity': 1.0,
    'unit_price': 10.25,
    'line_total': 0.0}]},
 {'invoice_number': '376739',
  'date': '06/17/2025',
  'vendor': 'Pacific Food Importers Inc.',
  'total_amount': 385.06,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT 50 LB',
    'quantity': 10.0001,
    'unit_price': 240.0,
    'line_total': 2400.024},
   {'description': 'EGGS LIQUID PAPETTIS HALF HALF MEDOSWEET 20 LB',
    'quantity': 1.0,
    'unit_price': 100.35,
    'line_total': 100.35},
   {'description': 'QT 4.376 LB',
    'quantity': 2.0,
    'unit_price': 665.0,
    'line_total': 33.0},
   {'description': 'GLOVE NITRILE XL 10',
    'quantity': 1.0,
    'unit_price': 35.361,
    'line_total': 35.36}]},
 {'invoice_number': '375991',
  'date': '06/03/2025',
  'vendor': 'Pacific Food Importers Inc.',
  'total_amount': 491.83,
  'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'FLOUR A/P UNBLEACHED GRAINCRAFT 50 LB',
    'quantity': 1.0,
    'unit_price': 21.0,
    'line_total': 21.0},
   {'description': 'FLOUR MEDIUM RYE 50 LB',
    'quantity': 1.0,
    'unit_price': 42.8,
    'line_total': 42.8},
   {'description': 'CORNMEAL YELLOW FINE 25 LB',
    'quantity': 1.0,
    'unit_price': 25.861,
    'line_total': 25.86},
   {'description': 'YEAST FRESH 20 * 16 OZ RED STAR',
    'quantity': 1.0,
    'unit_price': 58.06,
    'line_total': 58.06},
   {'description': 'SALT KOSHER COARSE DIAMOND CR 9 * 3 LB',
    'quantity': 9.0,
    'unit_price': 71.658,
    'line_total': 71.66},
   {'description': 'GLOVE NITRILE LARGE 10 X 100',
    'quantity': 1.0,
    'unit_price': 29.774,
    'line_total': 29.77},
   {'description': 'EGGS LIQUID PAPETTIS 2 * 20 LB',
    'quantity': 2.0,
    'unit_price': 25.09,
    'line_total': 50.18}]},
 {'invoice_number': '376355',
  'date': '06/10/2025',
  'vendor': 'Pacific Food Importers Inc',
  'total_amount': 688.51,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT',
    'quantity': 12.0,
    'unit_price': 24.063,
    'line_total': 288.0},
   {'description': 'BG MALT POWDER DIASTATIC+ RED STAR 0o0 JALAPENO SLICED #10 SAVOR',
    'quantity': 1.0,
    'unit_price': 119.177,
    'line_total': 119.18},
   {'description': '45.000 LB',
    'quantity': 1.0,
    'unit_price': 51.329,
    'line_total': 51.33},
   {'description': 'MILK OAT 12 oz',
    'quantity': 3.0,
    'unit_price': 39.948,
    'line_total': 119.84},
   {'description': 'SESAME SEEDS WHITE+ 4 * 5 LB MARCA CROC',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'SUGAR GRANULATED CANE 25 LB',
    'quantity': 1.0,
    'unit_price': 29.147,
    'line_total': 29.15}]},
 {'invoice_number': '376172',
  'date': '06/05/2025',
  'vendor': 'Pacific Food Importers Inc.',
  'total_amount': 133.42,
  'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20.000 LB',
    'quantity': 1.0,
    'unit_price': 133.418,
    'line_total': 133.42}]},
 {'invoice_number': '378093',
  'date': '07/15/2025',
  'vendor': 'Pacific Food Importers Inc.',
  'total_amount': 522.75,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT 50 LB',
    'quantity': 12.0,
    'unit_price': 24.0,
    'line_total': 288.0},
   {'description': 'CORNMEAL YELLOW FINE 25 LB',
    'quantity': 1.0,
    'unit_price': 25.1,
    'line_total': 25.1},
   {'description': 'GLOVE NITRILE MEDIUM x 100',
    'quantity': 1.0,
    'unit_price': 29.78,
    'line_total': 29.78},
   {'description': 'SESAME SEEDS WHITE+ MARCA CROC LB',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'POPPY SEED MARCA CROC 5.5 LB',
    'quantity': 1.0,
    'unit_price': 96.0,
    'line_total': 96.0},
   {'description': 'EGGS LIQUID PAPETTIS 20 LB',
    'quantity': 2.0,
    'unit_price': 47.6125,
    'line_total': 95.225}]},
 {'invoice_number': '20076301',
  'date': '7/28/2025',
  'vendor': "Frank's QQuality Produce",
  'total_amount': 78.12,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 12.0,
    'unit_price': 1.99,
    'line_total': 23.88},
   {'description': 'CUCUMBER, XFANCY LG',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'DILL BABY HERBS',
    'quantity': 6.0,
    'unit_price': 0.99,
    'line_total': 5.94},
   {'description': 'PARSLEY, ITALIAN',
    'quantity': 20.0,
    'unit_price': 0.99,
    'line_total': 19.8},
   {'description': 'ONION, GREEN',
    'quantity': 1.0,
    'unit_price': 10.0,
    'line_total': 10.0},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '20066901',
  'date': '5/22/2025',
  'vendor': "Frank's QQuality Produce",
  'total_amount': 75.14,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 10.0,
    'unit_price': 1.99,
    'line_total': 19.9},
   {'description': 'CUCUMBER, XFANCY LG',
    'quantity': 12.0,
    'unit_price': 0.9,
    'line_total': 10.8},
   {'description': 'ONION, GREEN',
    'quantity': 2.0,
    'unit_price': 10.0,
    'line_total': 20.0},
   {'description': 'HERBS, DILL BABY',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'HERBS, PARSLEY, ITALIAN BN',
    'quantity': 6.0,
    'unit_price': 0.99,
    'line_total': 5.94},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '20075310',
  'date': '7/21/2025',
  'vendor': "Frank's QQuality Produce",
  'total_amount': 74.26,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 12.0,
    'unit_price': 1.99,
    'line_total': 23.88},
   {'description': 'HERBS, DILL BABY',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'CUCUMBER, XFANCY LG',
    'quantity': 12.0,
    'unit_price': 0.99,
    'line_total': 11.88},
   {'description': 'ONION, GREEN',
    'quantity': 2.0,
    'unit_price': 10.0,
    'line_total': 20.0},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5},
   {'description': 'Sales Tax',
    'quantity': 0.0,
    'unit_price': 10.25,
    'line_total': 0.0}]},
 {'invoice_number': '375704',
  'date': '05/28/2025',
  'vendor': 'Pacific Food Importers Inc',
  'total_amount': 551.21,
  'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'JALAPENO SLICED #10 SAVOR SUGAR BROWN 25 LB WHITESATIN',
    'quantity': 1.0,
    'unit_price': 51.329,
    'line_total': 51.33},
   {'description': '26 . 000 LB',
    'quantity': 1.0,
    'unit_price': 26.778,
    'line_total': 26.0},
   {'description': 'MILK OAT 12 OATLEY EGGS LIQUID PAPETTIS',
    'quantity': 2.0,
    'unit_price': 39.948,
    'line_total': 79.0},
   {'description': 'X 20 LB',
    'quantity': 2.0,
    'unit_price': 100.35,
    'line_total': 200.0}]},
 {'invoice_number': '376485',
  'date': '06/11/2025',
  'vendor': 'Pacific Flood mporters INc',
  'total_amount': 133.42,
  'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20.000 LB',
    'quantity': 1.0,
    'unit_price': 133.42,
    'line_total': 133.42}]},
 {'invoice_number': '374941',
  'date': '05/13/2025',
  'vendor': 'Pacific Flood mporters INc',
  'total_amount': 289.85,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT 50 LB',
    'quantity': 10.0001,
    'unit_price': 24.063,
    'line_total': 240.0},
   {'description': 'CURRANTS LB',
    'quantity': 1.0,
    'unit_price': 16.588,
    'line_total': 16.59},
   {'description': 'GLOVE NITRILE LARGE 10',
    'quantity': 1.0,
    'unit_price': 29.774,
    'line_total': 29.77}]},
 {'invoice_number': '376462',
  'date': '06/11/2025',
  'vendor': 'Pacific Food Importers Inc',
  'total_amount': -133.42,
  'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20 -20 . 000 LB',
    'quantity': 1.0,
    'unit_price': 133.418,
    'line_total': -133.0}]},
 {'invoice_number': '379549',
  'date': '08/12/2025',
  'vendor': 'Pacific Food Importers Inc',
  'total_amount': 432.62,
  'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT',
    'quantity': 10.0001,
    'unit_price': 24.063,
    'line_total': 240.0},
   {'description': 'ALMOND BARISTA BLEND 12 * 32 CALIFIA EGGS LIQUID X 20 LB PAPETTIS',
    'quantity': 1.0,
    'unit_price': 41.139,
    'line_total': 41.14},
   {'description': 'LIMONATA CANS SAN PELLEG X 11 02',
    'quantity': 1.0,
    'unit_price': 95.225,
    'line_total': 95.23}]},
 {'invoice_number': '376462',
  'date': '06/11/2025',
  'vendor': 'Pacific Food Importers Inc.',
  'total_amount': -133.42,
  'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20',
    'quantity': 1.0,
    'unit_price': 133.42,
    'line_total': -133.42}]},
 {'invoice_number': '376486',
  'date': '06/11/2025',
  'vendor': 'Pacific Flood mporters INc',
  'total_amount': -54.62,
  'line_items': [{'description': 'YEAST FRESH RED STAR 20 X 16 Oz',
    'quantity': 1.0,
    'unit_price': 54.62,
    'line_total': -54.0}]},
 {'invoice_number': '376355',
  'date': '06/10/2025',
  'vendor': 'Pacific Flood Importers Inc',
  'total_amount': 688.51,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT',
    'quantity': 12.0,
    'unit_price': 24.063,
    'line_total': 288.0},
   {'description': 'MALT POWDER DIASTATIC+ RED STAR 0o0 JALAPENO SLICED #10 SAVOR',
    'quantity': 1.0,
    'unit_price': 119.177,
    'line_total': 119.18},
   {'description': 'MALT POWDER NON-DIASTATIC',
    'quantity': 1.0,
    'unit_price': 51.329,
    'line_total': 51.33},
   {'description': 'MILK OAT 12',
    'quantity': 3.0,
    'unit_price': 39.948,
    'line_total': 119.84},
   {'description': 'SESAME SEEDS WHITE+ 4 * 5 LB MARCA CROC',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'SUGAR GRANULATED CANE 25 LB',
    'quantity': 1.0,
    'unit_price': 29.147,
    'line_total': 29.15}]},
 {'invoice_number': '20075310',
  'date': '7/21/2025',
  'vendor': "Frank's QQuality Produce",
  'total_amount': 74.26,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 12.0,
    'unit_price': 1.99,
    'line_total': 23.88},
   {'description': 'HERBS, DILL BABY',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'CUCUMBER, XFANCY LG',
    'quantity': 12.0,
    'unit_price': 0.99,
    'line_total': 11.88},
   {'description': 'ONION, GREEN',
    'quantity': 2.0,
    'unit_price': 10.0,
    'line_total': 20.0},
   {'description': 'BAG FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5},
   {'description': 'Sales Tax',
    'quantity': 0.0,
    'unit_price': 0.0,
    'line_total': 0.0}]},
 {'invoice_number': '377101',
  'date': '06/24/2025',
  'vendor': 'Pacific Food Importers Inc.',
  'total_amount': 738.17,
  'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'PAN SPRAY PREHIUM 6 * 14 02 VEGALENE SALT KOSHER COARSE 9 * 3 LB DIAMOND CR',
    'quantity': 1.0,
    'unit_price': 34.038,
    'line_total': 34.0},
   {'description': '',
    'quantity': 1.0,
    'unit_price': 75.076,
    'line_total': 75.0},
   {'description': 'ONION MINCED 4 * 4.5 LB MARCA CROC GARLIC MINCED LB MARCA CROC',
    'quantity': 1.0,
    'unit_price': 104.0,
    'line_total': 104.0},
   {'description': '',
    'quantity': 1.0,
    'unit_price': 112.0,
    'line_total': 112.0},
   {'description': 'SESAME SEEDS WHITE+ 4 * 5 LB MARCA CROC',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'MILK ALMOND PACIFIC 12 * 32 Oz',
    'quantity': 1.0,
    'unit_price': 35.152,
    'line_total': 35.152},
   {'description': 'MILK OAT 12 0z OATLEY',
    'quantity': 1.0,
    'unit_price': 39.948,
    'line_total': 39.0},
   {'description': 'EGGS LIQUID 2 * 20 LB PAPETTIS',
    'quantity': 1.0,
    'unit_price': 100.35,
    'line_total': 100.35}]},
 {'invoice_number': '20077622',
  'date': '8/6/2025',
  'vendor': "Frank's QQuality Produce",
  'total_amount': 79.11,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 12.0,
    'unit_price': 1.99,
    'line_total': 23.88},
   {'description': 'DILL BABY HERBS',
    'quantity': 6.0,
    'unit_price': 0.99,
    'line_total': 5.94},
   {'description': 'PARSLEY',
    'quantity': 14.0,
    'unit_price': 0.99,
    'line_total': 13.86},
   {'description': 'ITALIAN BN',
    'quantity': 7.0,
    'unit_price': 0.99,
    'line_total': 6.93},
   {'description': 'CUCUMBER',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'ONION, GREEN',
    'quantity': 1.0,
    'unit_price': 10.0,
    'line_total': 10.0},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '20074433',
  'date': '7/15/2025',
  'vendor': "Frank's QQuality Produce",
  'total_amount': 45.28,
  'line_items': [{'description': 'CUCUMBER, XFANCY LG',
    'quantity': 12.0,
    'unit_price': 0.99,
    'line_total': 11.88},
   {'description': 'TOMATO, ROMA',
    'quantity': 5.0,
    'unit_price': 1.99,
    'line_total': 9.95},
   {'description': 'HERBS, DILL',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'BABY ONION, ITALIAN',
    'quantity': 5.0,
    'unit_price': 0.99,
    'line_total': 4.95},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '2825',
  'date': '7/28/2025',
  'vendor': "Frank's QQuality Produce",
  'total_amount': 78.12,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 12.0,
    'unit_price': 1.99,
    'line_total': 23.88},
   {'description': 'HERBS',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'DILL BABY HERBS',
    'quantity': 6.0,
    'unit_price': 0.99,
    'line_total': 5.94},
   {'description': 'ITALIAN BN',
    'quantity': 20.0,
    'unit_price': 0.99,
    'line_total': 19.8},
   {'description': 'CUCUMBER, XFANCY',
    'quantity': 1.0,
    'unit_price': 10.0,
    'line_total': 10.0},
   {'description': 'LG EA ONION, GREEN',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '378094',
  'date': '07/15/2025',
  'vendor': 'Pacific Flood mporters INc',
  'total_amount': 75.08,
  'line_items': [{'description': 'SALT KOSHER COARSE DIAMOND CR X 3 LB',
    'quantity': 1.0,
    'unit_price': 75.076,
    'line_total': 75.0}]},
 {'invoice_number': '20078834',
  'date': '8/14/2025',
  'vendor': "Frank's QQuality Produce",
  'total_amount': 53.35,
  'line_items': [{'description': 'ONION, GREEN',
    'quantity': 2.0,
    'unit_price': 10.0,
    'line_total': 20.0},
   {'description': 'CUCUMBER, XFANCY LG',
    'quantity': 15.0,
    'unit_price': 0.99,
    'line_total': 14.85},
   {'description': 'HERBS, DILL BABY',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '375298',
  'date': '05/20/2025',
  'vendor': 'Pacific Flood Importers Inc',
  'total_amount': 357.8,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT',
    'quantity': 8.0,

In [ ]:
import pandas as pd

In [ ]:
df=pd.read_json("/content/all_invoices.json")
df

,invoice_number,date,vendor,total_amount,line_items
0,378793,2025-07-29,Pacific Food Importers Inc.,754.89,[{'description': 'FLOUR POWER GRAINCRAFT 50 LB...
1,376172,2025-06-05,Pacific Flood mporters INc,133.42,[{'description': 'YEAST INSTANT RED LBL SAF 20...
2,375991,2025-06-03,Pacific Flood Importers Inc,491.83,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
3,20078834,2025-08-14,Frank's QQuality Produce,53.35,"[{'description': 'ONION, GREEN', 'quantity': 2..."
4,378483,2025-07-22,Pacific Flood mporters INc,576.63,"[{'description': 'FLOUR POWER GRAINCRAFT LB', ..."
5,20077622,2025-08-06,Frank's QQuality Produce,79.11,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
6,376739,2025-06-17,Pacific Food Importers Inc.,385.06,[{'description': 'FLOUR POWER GRAINCRAFT 50 LB...
7,375991,2025-06-03,Pacific Food Importers Inc.,491.83,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
8,376355,2025-06-10,Pacific Food Importers Inc,688.51,"[{'description': 'FLOUR POWER GRAINCRAFT', 'qu..."
9,376172,2025-06-05,Pacific Food Importers Inc.,133.42,[{'description': 'YEAST INSTANT RED LBL SAF 20...
10,378093,2025-07-15,Pacific Food Importers Inc.,522.75,[{'description': 'FLOUR POWER GRAINCRAFT 50 LB...
11,20076301,2025-07-28,Frank's QQuality Produce,78.12,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
12,20066901,2025-05-22,Frank's QQuality Produce,75.14,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
13,20075310,2025-07-21,Frank's QQuality Produce,74.26,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
14,375704,2025-05-28,Pacific Food Importers Inc,551.21,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
15,376485,2025-06-11,Pacific Flood mporters INc,133.42,[{'description': 'YEAST INSTANT RED LBL SAF 20...
16,374941,2025-05-13,Pacific Flood mporters INc,289.85,[{'description': 'FLOUR POWER GRAINCRAFT 50 LB...
17,376462,2025-06-11,Pacific Food Importers Inc,-133.42,[{'description': 'YEAST INSTANT RED LBL SAF 20...
18,379549,2025-08-12,Pacific Food Importers Inc,432.62,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
19,376462,2025-06-11,Pacific Food Importers Inc.,-133.42,[{'description': 'YEAST INSTANT RED LBL SAF 20...
20,376486,2025-06-11,Pacific Flood mporters INc,-54.62,[{'description': 'YEAST FRESH RED STAR 20 X 16...
21,376355,2025-06-10,Pacific Flood Importers Inc,688.51,"[{'description': 'FLOUR POWER GRAINCRAFT', 'qu..."
22,20075310,2025-07-21,Frank's QQuality Produce,74.26,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
23,377101,2025-06-24,Pacific Food Importers Inc.,738.17,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
24,20077622,2025-08-06,Frank's QQuality Produce,79.11,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
25,20074433,2025-07-15,Frank's QQuality Produce,45.28,"[{'description': 'CUCUMBER, XFANCY LG', 'quant..."
26,2825,2025-07-28,Frank's QQuality Produce,78.12,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
27,378094,2025-07-15,Pacific Flood mporters INc,75.08,[{'description': 'SALT KOSHER COARSE DIAMOND C...
28,20078834,2025-08-14,Frank's QQuality Produce,53.35,"[{'description': 'ONION, GREEN', 'quantity': 2..."
29,375298,2025-05-20,Pacific Flood Importers Inc,357.80,"[{'description': 'FLOUR POWER GRAINCRAFT', 'qu..."
30,20065629,2025-05-13,Frank's QQuality Produce,109.26,"[{'description': 'TOMATO, ROMA', 'quantity': 8..."
31,20068140,2025-05-30,Frank's QQuality Produce,75.14,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
32,376173,2025-06-05,Pacific Flood mporters INc,100.35,[{'description': 'EGGS LIQUID PAPETTIS X 20 LB...
33,376173,2025-06-05,Pacific Food Importers Inc.,100.35,[{'description': 'EGGS LIQUID PAPETTIS X 20 LB...
34,378262,2025-07-17,Pacific Flood mporters INc,95.23,[{'description': 'EGGS LIQUID PAPETTIS X 20 LB...
35,20074433,2025-07-15,Frank's QQuality Produce,45.28,"[{'description': 'CUCUMBER, XFANCY LG', 'quant..."
36,376485,2025-06-11,Pacific Flood mporters INc,133.42,"[{'description': 'YEAST INSTANT RED LBL SAF', ..."
37,379183,2025-08-05,Pacific Food Importers Inc.,596.94,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
38,377184,2025-06-25,Pacific Flood mporters INc,41.14,[{'description': 'ALMOND BARISTA BLEND CALIFIA...
39,20072265,2025-06-27,Frank's QQuality Produce,63.34,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
40,378206,2025-07-16,Pacific Flood mporters INc,95.23,[{'description': 'EGGS LIQUID PAPETTIS X 20 LB...
41,377765,2025-07-08,Pacific Food Importers Inc.,557.38,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
42,376063,2025-06-04,Pacific Flood mporters INc,35.00,[{'description': 'EGGS LIQUID PAPETTIS X 20 LB...
43,20072898,2025-07-03,Frank's QQuality Produce,82.09,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
44,376063,2025-06-04,Pacific Flood Importers Inc,35.00,[{'description': 'EGGS LIQUID PAPETTIS X 20 LB...
45,376486,2025-06-11,Pacific Food Importers Inc.,-54.62,[{'description': 'YEAST FRESH RED STAR 20 X 16...
46,20068978,2025-06-05,Frank's QQuality Produce,90.12,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
47,20071084,2025-06-20,Frank's QQuality Produce,79.12,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."

In [ ]:
df.to_csv("invioce.csv")

In [ ]:
s=pd.read_csv("/content/invioce.csv")
s

,Unnamed: 0,invoice_number,date,vendor,total_amount,line_items
0,0,378793,2025-07-29,Pacific Food Importers Inc.,754.89,[{'description': 'FLOUR POWER GRAINCRAFT 50 LB...
1,1,376172,2025-06-05,Pacific Flood mporters INc,133.42,[{'description': 'YEAST INSTANT RED LBL SAF 20...
2,2,375991,2025-06-03,Pacific Flood Importers Inc,491.83,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
3,3,20078834,2025-08-14,Frank's QQuality Produce,53.35,"[{'description': 'ONION, GREEN', 'quantity': 2..."
4,4,378483,2025-07-22,Pacific Flood mporters INc,576.63,"[{'description': 'FLOUR POWER GRAINCRAFT LB', ..."
5,5,20077622,2025-08-06,Frank's QQuality Produce,79.11,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
6,6,376739,2025-06-17,Pacific Food Importers Inc.,385.06,[{'description': 'FLOUR POWER GRAINCRAFT 50 LB...
7,7,375991,2025-06-03,Pacific Food Importers Inc.,491.83,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
8,8,376355,2025-06-10,Pacific Food Importers Inc,688.51,"[{'description': 'FLOUR POWER GRAINCRAFT', 'qu..."
9,9,376172,2025-06-05,Pacific Food Importers Inc.,133.42,[{'description': 'YEAST INSTANT RED LBL SAF 20...
10,10,378093,2025-07-15,Pacific Food Importers Inc.,522.75,[{'description': 'FLOUR POWER GRAINCRAFT 50 LB...
11,11,20076301,2025-07-28,Frank's QQuality Produce,78.12,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
12,12,20066901,2025-05-22,Frank's QQuality Produce,75.14,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
13,13,20075310,2025-07-21,Frank's QQuality Produce,74.26,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
14,14,375704,2025-05-28,Pacific Food Importers Inc,551.21,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
15,15,376485,2025-06-11,Pacific Flood mporters INc,133.42,[{'description': 'YEAST INSTANT RED LBL SAF 20...
16,16,374941,2025-05-13,Pacific Flood mporters INc,289.85,[{'description': 'FLOUR POWER GRAINCRAFT 50 LB...
17,17,376462,2025-06-11,Pacific Food Importers Inc,-133.42,[{'description': 'YEAST INSTANT RED LBL SAF 20...
18,18,379549,2025-08-12,Pacific Food Importers Inc,432.62,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
19,19,376462,2025-06-11,Pacific Food Importers Inc.,-133.42,[{'description': 'YEAST INSTANT RED LBL SAF 20...
20,20,376486,2025-06-11,Pacific Flood mporters INc,-54.62,[{'description': 'YEAST FRESH RED STAR 20 X 16...
21,21,376355,2025-06-10,Pacific Flood Importers Inc,688.51,"[{'description': 'FLOUR POWER GRAINCRAFT', 'qu..."
22,22,20075310,2025-07-21,Frank's QQuality Produce,74.26,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
23,23,377101,2025-06-24,Pacific Food Importers Inc.,738.17,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
24,24,20077622,2025-08-06,Frank's QQuality Produce,79.11,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
25,25,20074433,2025-07-15,Frank's QQuality Produce,45.28,"[{'description': 'CUCUMBER, XFANCY LG', 'quant..."
26,26,2825,2025-07-28,Frank's QQuality Produce,78.12,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
27,27,378094,2025-07-15,Pacific Flood mporters INc,75.08,[{'description': 'SALT KOSHER COARSE DIAMOND C...
28,28,20078834,2025-08-14,Frank's QQuality Produce,53.35,"[{'description': 'ONION, GREEN', 'quantity': 2..."
29,29,375298,2025-05-20,Pacific Flood Importers Inc,357.80,"[{'description': 'FLOUR POWER GRAINCRAFT', 'qu..."
30,30,20065629,2025-05-13,Frank's QQuality Produce,109.26,"[{'description': 'TOMATO, ROMA', 'quantity': 8..."
31,31,20068140,2025-05-30,Frank's QQuality Produce,75.14,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
32,32,376173,2025-06-05,Pacific Flood mporters INc,100.35,[{'description': 'EGGS LIQUID PAPETTIS X 20 LB...
33,33,376173,2025-06-05,Pacific Food Importers Inc.,100.35,[{'description': 'EGGS LIQUID PAPETTIS X 20 LB...
34,34,378262,2025-07-17,Pacific Flood mporters INc,95.23,[{'description': 'EGGS LIQUID PAPETTIS X 20 LB...
35,35,20074433,2025-07-15,Frank's QQuality Produce,45.28,"[{'description': 'CUCUMBER, XFANCY LG', 'quant..."
36,36,376485,2025-06-11,Pacific Flood mporters INc,133.42,"[{'description': 'YEAST INSTANT RED LBL SAF', ..."
37,37,379183,2025-08-05,Pacific Food Importers Inc.,596.94,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
38,38,377184,2025-06-25,Pacific Flood mporters INc,41.14,[{'description': 'ALMOND BARISTA BLEND CALIFIA...
39,39,20072265,2025-06-27,Frank's QQuality Produce,63.34,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
40,40,378206,2025-07-16,Pacific Flood mporters INc,95.23,[{'description': 'EGGS LIQUID PAPETTIS X 20 LB...
41,41,377765,2025-07-08,Pacific Food Importers Inc.,557.38,[{'description': 'FLOUR POWER 50 LB GRAINCRAFT...
42,42,376063,2025-06-04,Pacific Flood mporters INc,35.00,[{'description': 'EGGS LIQUID PAPETTIS X 20 LB...
43,43,20072898,2025-07-03,Frank's QQuality Produce,82.09,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
44,44,376063,2025-06-04,Pacific Flood Importers Inc,35.00,[{'description': 'EGGS LIQUID PAPETTIS X 20 LB...
45,45,376486,2025-06-11,Pacific Food Importers Inc.,-54.62,[{'description': 'YEAST FRESH RED STAR 20 X 16...
46,46,20068978,2025-06-05,Frank's QQuality Produce,90.12,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."
47,47,20071084,2025-06-20,Frank's QQuality Produce,79.12,"[{'description': 'TOMATO, ROMA', 'quantity': 1..."

In [ ]:
df.to_csv("invoices.csv",index=False)

In [ ]:
import pandas as pd

In [ ]:
import json

with open("/content/all_invoices.json", "r") as file:
    data = json.load(file)

print(data)

[{'invoice_number': '378793', 'date': '07/29/2025', 'vendor': 'Pacific Food Importers Inc.', 'total_amount': 754.89, 'line_items': [{'description': 'FLOUR POWER GRAINCRAFT 50 LB', 'quantity': 10.0001, 'unit_price': 24.063, 'line_total': 240.0}, {'description': 'ONION MINCED MARCA CROC 4 * 4 .5 LB', 'quantity': 1.0, 'unit_price': 113.333, 'line_total': 113.33}, {'description': 'SESAME SEEDS MHITE+ MARCA CROC 4 LB', 'quantity': 1.0, 'unit_price': 80.25, 'line_total': 80.25}, {'description': 'SALT KOSHER COARSE DIAMOND CR 3 LB', 'quantity': 2.0, 'unit_price': 75.076, 'line_total': 150.15}, {'description': 'GLOVE NITRILE XL 10 100 ct', 'quantity': 1.0, 'unit_price': 36.25, 'line_total': 36.25}, {'description': 'YEAST INSTANT RED LBL SAF 20', 'quantity': 1.0, 'unit_price': 130.0, 'line_total': 130.0}]}, {'invoice_number': '376172', 'date': '06/05/2025', 'vendor': 'Pacific Flood mporters INc', 'total_amount': 133.42, 'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20.000 LB', 'quantity': 1.0, 'unit_price': 133.418, 'line_total': 133.0}]}, {'invoice_number': '375991', 'date': '06/03/2025', 'vendor': 'Pacific Flood Importers Inc', 'total_amount': 491.83, 'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT', 'quantity': 8.0, 'unit_price': 24.063, 'line_total': 192.5}, {'description': 'FLOUR A/P UNBLEACHED GRAINCRAFT', 'quantity': 1.0, 'unit_price': 21.0, 'line_total': 21.0}, {'description': 'FLOUR MEDIUM RYE', 'quantity': 1.0, 'unit_price': 42.8, 'line_total': 42.8}, {'description': 'FLOUR MEDIUM RYE', 'quantity': 1.0, 'unit_price': 42.8, 'line_total': 42.8}, {'description': 'CORNMEAL YELLOH FINE** * 25 LB', 'quantity': 1.0, 'unit_price': 25.86, 'line_total': 25.86}, {'description': 'SALT KOSHER COARSE DIAMOND CR', 'quantity': 9.0, 'unit_price': 7.962, 'line_total': 71.66}, {'description': 'GLOVE NITRILE LARGE 10 X 100', 'quantity': 1.0, 'unit_price': 29.77, 'line_total': 29.77}, {'description': 'EGGS LIQUID PAPETTIS', 'quantity': 1.0, 'unit_price': 50.18, 'line_total': 50.18}]}, {'invoice_number': '20078834', 'date': '8/14/2025', 'vendor': "Frank's QQuality Produce", 'total_amount': 53.35, 'line_items': [{'description': 'ONION, GREEN', 'quantity': 2.0, 'unit_price': 10.0, 'line_total': 20.0}, {'description': 'CUCUMBER, XFANCY LG', 'quantity': 15.0, 'unit_price': 0.99, 'line_total': 14.85}, {'description': 'HERBS, DILL BABY', 'quantity': 1.0, 'unit_price': 11.0, 'line_total': 11.0}, {'description': 'FUEL SURCHARGE', 'quantity': 1.0, 'unit_price': 7.5, 'line_total': 7.5}]}, {'invoice_number': '378483', 'date': '07/22/2025', 'vendor': 'Pacific Flood mporters INc', 'total_amount': 576.63, 'line_items': [{'description': 'FLOUR POWER GRAINCRAFT LB', 'quantity': 10.0001, 'unit_price': 24.063, 'line_total': 240.0}, {'description': 'MALT POWDER DIASTATIC+ RED STAR JALAPENO SLICED #10 SAVOR LB', 'quantity': 1.0, 'unit_price': 116.848, 'line_total': 116.85}, {'description': '45.000 LB', 'quantity': 1.0, 'unit_price': 329.0, 'line_total': 51.33}, {'description': 'GLOVE NITRILE MEDIUM', 'quantity': 1.0, 'unit_price': 29.78, 'line_total': 29.78}, {'description': 'EGGS LIQUID PAPETTIS X 20 LB', 'quantity': 1.0, 'unit_price': 95.225, 'line_total': 95.23}]}, {'invoice_number': '20077622', 'date': '8/6/2025', 'vendor': "Frank's QQuality Produce", 'total_amount': 79.11, 'line_items': [{'description': 'TOMATO, ROMA', 'quantity': 12.0, 'unit_price': 1.99, 'line_total': 23.88}, {'description': 'HERBS, DILL BABY HERBS, PARSLEY, ITALIAN', 'quantity': 1.0, 'unit_price': 11.0, 'line_total': 11.0}, {'description': 'CUCUMBER, XFANCY', 'quantity': 6.0, 'unit_price': 0.99, 'line_total': 5.94}, {'description': 'ONION, GREEN', 'quantity': 14.0, 'unit_price': 0.99, 'line_total': 13.86}, {'description': 'ONION, ITALIAN RED', 'quantity': 1.0, 'unit_price': 10.0, 'line_total': 10.0}, {'description': 'BAG ONION, ITALIAN RED', 'quantity': 7.0, 'unit_price': 0.99, 'line_total': 6.93}, {'description': 'FUEL SURCHARGE', 'quantity': 1.0, 'unit_price': 7.5, 'line_total': 7.5}, {'description': 'Sales Tax', 'quantity': 1.0, 'unit_price': 10.25, 'line_total': 0.0}]}, {'invoice_number': '376739', 'date': '06/17/2025', 'vendor': 'Pacific Food Importers Inc.', 'total_amount': 385.06, 'line_items': [{'description': 'FLOUR POWER GRAINCRAFT 50 LB', 'quantity': 10.0001, 'unit_price': 240.0, 'line_total': 2400.024}, {'description': 'EGGS LIQUID PAPETTIS HALF HALF MEDOSWEET 20 LB', 'quantity': 1.0, 'unit_price': 100.35, 'line_total': 100.35}, {'description': 'QT 4.376 LB', 'quantity': 2.0, 'unit_price': 665.0, 'line_total': 33.0}, {'description': 'GLOVE NITRILE XL 10', 'quantity': 1.0, 'unit_price': 35.361, 'line_total': 35.36}]}, {'invoice_number': '375991', 'date': '06/03/2025', 'vendor': 'Pacific Food Importers Inc.', 'total_amount': 491.83, 'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT', 'quantity': 8.0, 'unit_price': 24.063, 'line_total': 192.5}, {'description': 'FLOUR A/P UNBLEACHED GRAINCRAFT 50 LB', 'quantity': 1.0, 'unit_price': 21.0, 'line_total': 21.0}, {'description': 'FLOUR MEDIUM RYE 50 LB', 'quantity': 1.0, 'unit_price': 42.8, 'line_total': 42.8}, {'description': 'CORNMEAL YELLOW FINE 25 LB', 'quantity': 1.0, 'unit_price': 25.861, 'line_total': 25.86}, {'description': 'YEAST FRESH 20 * 16 OZ RED STAR', 'quantity': 1.0, 'unit_price': 58.06, 'line_total': 58.06}, {'description': 'SALT KOSHER COARSE DIAMOND CR 9 * 3 LB', 'quantity': 9.0, 'unit_price': 71.658, 'line_total': 71.66}, {'description': 'GLOVE NITRILE LARGE 10 X 100', 'quantity': 1.0, 'unit_price': 29.774, 'line_total': 29.77}, {'description': 'EGGS LIQUID PAPETTIS 2 * 20 LB', 'quantity': 2.0, 'unit_price': 25.09, 'line_total': 50.18}]}, {'invoice_number': '376355', 'date': '06/10/2025', 'vendor': 'Pacific Food Importers Inc', 'total_amount': 688.51, 'line_items': [{'description': 'FLOUR POWER GRAINCRAFT', 'quantity': 12.0, 'unit_price': 24.063, 'line_total': 288.0}, {'description': 'BG MALT POWDER DIASTATIC+ RED STAR 0o0 JALAPENO SLICED #10 SAVOR', 'quantity': 1.0, 'unit_price': 119.177, 'line_total': 119.18}, {'description': '45.000 LB', 'quantity': 1.0, 'unit_price': 51.329, 'line_total': 51.33}, {'description': 'MILK OAT 12 oz', 'quantity': 3.0, 'unit_price': 39.948, 'line_total': 119.84}, {'description': 'SESAME SEEDS WHITE+ 4 * 5 LB MARCA CROC', 'quantity': 1.0, 'unit_price': 80.25, 'line_total': 80.25}, {'description': 'SUGAR GRANULATED CANE 25 LB', 'quantity': 1.0, 'unit_price': 29.147, 'line_total': 29.15}]}, {'invoice_number': '376172', 'date': '06/05/2025', 'vendor': 'Pacific Food Importers Inc.', 'total_amount': 133.42, 'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20.000 LB', 'quantity': 1.0, 'unit_price': 133.418, 'line_total': 133.42}]}, {'invoice_number': '378093', 'date': '07/15/2025', 'vendor': 'Pacific Food Importers Inc.', 'total_amount': 522.75, 'line_items': [{'description': 'FLOUR POWER GRAINCRAFT 50 LB', 'quantity': 12.0, 'unit_price': 24.0, 'line_total': 288.0}, {'description': 'CORNMEAL YELLOW FINE 25 LB', 'quantity': 1.0, 'unit_price': 25.1, 'line_total': 25.1}, {'description': 'GLOVE NITRILE MEDIUM x 100', 'quantity': 1.0, 'unit_price': 29.78, 'line_total': 29.78}, {'description': 'SESAME SEEDS WHITE+ MARCA CROC LB', 'quantity': 1.0, 'unit_price': 80.25, 'line_total': 80.25}, {'description': 'POPPY SEED MARCA CROC 5.5 LB', 'quantity': 1.0, 'unit_price': 96.0, 'line_total': 96.0}, {'description': 'EGGS LIQUID PAPETTIS 20 LB', 'quantity': 2.0, 'unit_price': 47.6125, 'line_total': 95.225}]}, {'invoice_number': '20076301', 'date': '7/28/2025', 'vendor': "Frank's QQuality Produce", 'total_amount': 78.12, 'line_items': [{'description': 'TOMATO, ROMA', 'quantity': 12.0, 'unit_price': 1.99, 'line_total': 23.88}, {'description': 'CUCUMBER, XFANCY LG', 'quantity': 1.0, 'unit_price': 11.0, 'line_total': 11.0}, {'description': 'DILL BABY HERBS', 'quantity': 6.0, 'unit_price': 0.99, 'line_total': 5.94}, {'description': 'PARSLEY, ITALIAN', 'quantity': 20.0, 'unit_price': 0.99, 'line_total': 19.8}, {'description': 'ONION, GREEN', 'quantity': 1.0, 'unit_price': 10.0, 'line_total': 10.0}, {'description': 'FUEL SURCHARGE', 'quantity': 1.0, 'unit_price': 7.5, 'line_total': 7.5}]}, {'invoice_number': '20066901', 'date': '5/22/2025', 'vendor': "Frank's QQuality Produce", 'total_amount': 75.14, 'line_items': [{'description': 'TOMATO, ROMA', 'quantity': 10.0, 'unit_price': 1.99, 'line_total': 19.9}, {'description': 'CUCUMBER, XFANCY LG', 'quantity': 12.0, 'unit_price': 0.9, 'line_total': 10.8}, {'description': 'ONION, GREEN', 'quantity': 2.0, 'unit_price': 10.0, 'line_total': 20.0}, {'description': 'HERBS, DILL BABY', 'quantity': 1.0, 'unit_price': 11.0, 'line_total': 11.0}, {'description': 'HERBS, PARSLEY, ITALIAN BN', 'quantity': 6.0, 'unit_price': 0.99, 'line_total': 5.94}, {'description': 'FUEL SURCHARGE', 'quantity': 1.0, 'unit_price': 7.5, 'line_total': 7.5}]}, {'invoice_number': '20075310', 'date': '7/21/2025', 'vendor': "Frank's QQuality Produce", 'total_amount': 74.26, 'line_items': [{'description': 'TOMATO, ROMA', 'quantity': 12.0, 'unit_price': 1.99, 'line_total': 23.88}, {'description': 'HERBS, DILL BABY', 'quantity': 1.0, 'unit_price': 11.0, 'line_total': 11.0}, {'description': 'CUCUMBER, XFANCY LG', 'quantity': 12.0, 'unit_price': 0.99, 'line_total': 11.88}, {'description': 'ONION, GREEN', 'quantity': 2.0, 'unit_price': 10.0, 'line_total': 20.0}, {'description': 'FUEL SURCHARGE', 'quantity': 1.0, 'unit_price': 7.5, 'line_total': 7.5}, {'description': 'Sales Tax', 'quantity': 0.0, 'unit_price': 10.25, 'line_total': 0.0}]}, {'invoice_number': '375704', 'date': '05/28/2025', 'vendor': 'Pacific Food Importers Inc', 'total_amount': 551.21, 'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT', 'quantity': 8.0, 'unit_price': 24.063, 'line_total': 192.5}, {'description': 'JALAPENO SLICED #10 SAVOR SUGAR BROWN 25 LB WHITESATIN', 'quantity': 1.0, 'unit_price': 51.329, 'line_total': 51.33}, {'description': '26 . 000 LB', 'quantity': 1.0, 'unit_price': 26.778, 'line_total': 26.0}, {'description': 'MILK OAT 12 OATLEY EGGS LIQUID PAPETTIS', 'quantity': 2.0, 'unit_price': 39.948, 'line_total': 79.0}, {'description': 'X 20 LB', 'quantity': 2.0, 'unit_price': 100.35, 'line_total': 200.0}]}, {'invoice_number': '376485', 'date': '06/11/2025', 'vendor': 'Pacific Flood mporters INc', 'total_amount': 133.42, 'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20.000 LB', 'quantity': 1.0, 'unit_price': 133.42, 'line_total': 133.42}]}, {'invoice_number': '374941', 'date': '05/13/2025', 'vendor': 'Pacific Flood mporters INc', 'total_amount': 289.85, 'line_items': [{'description': 'FLOUR POWER GRAINCRAFT 50 LB', 'quantity': 10.0001, 'unit_price': 24.063, 'line_total': 240.0}, {'description': 'CURRANTS LB', 'quantity': 1.0, 'unit_price': 16.588, 'line_total': 16.59}, {'description': 'GLOVE NITRILE LARGE 10', 'quantity': 1.0, 'unit_price': 29.774, 'line_total': 29.77}]}, {'invoice_number': '376462', 'date': '06/11/2025', 'vendor': 'Pacific Food Importers Inc', 'total_amount': -133.42, 'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20 -20 . 000 LB', 'quantity': 1.0, 'unit_price': 133.418, 'line_total': -133.0}]}, {'invoice_number': '379549', 'date': '08/12/2025', 'vendor': 'Pacific Food Importers Inc', 'total_amount': 432.62, 'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT', 'quantity': 10.0001, 'unit_price': 24.063, 'line_total': 240.0}, {'description': 'ALMOND BARISTA BLEND 12 * 32 CALIFIA EGGS LIQUID X 20 LB PAPETTIS', 'quantity': 1.0, 'unit_price': 41.139, 'line_total': 41.14}, {'description': 'LIMONATA CANS SAN PELLEG X 11 02', 'quantity': 1.0, 'unit_price': 95.225, 'line_total': 95.23}]}, {'invoice_number': '376462', 'date': '06/11/2025', 'vendor': 'Pacific Food Importers Inc.', 'total_amount': -133.42, 'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20', 'quantity': 1.0, 'unit_price': 133.42, 'line_total': -133.42}]}, {'invoice_number': '376486', 'date': '06/11/2025', 'vendor': 'Pacific Flood mporters INc', 'total_amount': -54.62, 'line_items': [{'description': 'YEAST FRESH RED STAR 20 X 16 Oz', 'quantity': 1.0, 'unit_price': 54.62, 'line_total': -54.0}]}, {'invoice_number': '376355', 'date': '06/10/2025', 'vendor': 'Pacific Flood Importers Inc', 'total_amount': 688.51, 'line_items': [{'description': 'FLOUR POWER GRAINCRAFT', 'quantity': 12.0, 'unit_price': 24.063, 'line_total': 288.0}, {'description': 'MALT POWDER DIASTATIC+ RED STAR 0o0 JALAPENO SLICED #10 SAVOR', 'quantity': 1.0, 'unit_price': 119.177, 'line_total': 119.18}, {'description': 'MALT POWDER NON-DIASTATIC', 'quantity': 1.0, 'unit_price': 51.329, 'line_total': 51.33}, {'description': 'MILK OAT 12', 'quantity': 3.0, 'unit_price': 39.948, 'line_total': 119.84}, {'description': 'SESAME SEEDS WHITE+ 4 * 5 LB MARCA CROC', 'quantity': 1.0, 'unit_price': 80.25, 'line_total': 80.25}, {'description': 'SUGAR GRANULATED CANE 25 LB', 'quantity': 1.0, 'unit_price': 29.147, 'line_total': 29.15}]}, {'invoice_number': '20075310', 'date': '7/21/2025', 'vendor': "Frank's QQuality Produce", 'total_amount': 74.26, 'line_items': [{'description': 'TOMATO, ROMA', 'quantity': 12.0, 'unit_price': 1.99, 'line_total': 23.88}, {'description': 'HERBS, DILL BABY', 'quantity': 1.0, 'unit_price': 11.0, 'line_total': 11.0}, {'description': 'CUCUMBER, XFANCY LG', 'quantity': 12.0, 'unit_price': 0.99, 'line_total': 11.88}, {'description': 'ONION, GREEN', 'quantity': 2.0, 'unit_price': 10.0, 'line_total': 20.0}, {'description': 'BAG FUEL SURCHARGE', 'quantity': 1.0, 'unit_price': 7.5, 'line_total': 7.5}, {'description': 'Sales Tax', 'quantity': 0.0, 'unit_price': 0.0, 'line_total': 0.0}]}, {'invoice_number': '377101', 'date': '06/24/2025', 'vendor': 'Pacific Food Importers Inc.', 'total_amount': 738.17, 'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT', 'quantity': 8.0, 'unit_price': 24.063, 'line_total': 192.5}, {'description': 'PAN SPRAY PREHIUM 6 * 14 02 VEGALENE SALT KOSHER COARSE 9 * 3 LB DIAMOND CR', 'quantity': 1.0, 'unit_price': 34.038, 'line_total': 34.0}, {'description': '', 'quantity': 1.0, 'unit_price': 75.076, 'line_total': 75.0}, {'description': 'ONION MINCED 4 * 4.5 LB MARCA CROC GARLIC MINCED LB MARCA CROC', 'quantity': 1.0, 'unit_price': 104.0, 'line_total': 104.0}, {'description': '', 'quantity': 1.0, 'unit_price': 112.0, 'line_total': 112.0}, {'description': 'SESAME SEEDS WHITE+ 4 * 5 LB MARCA CROC', 'quantity': 1.0, 'unit_price': 80.25, 'line_total': 80.25}, {'description': 'MILK ALMOND PACIFIC 12 * 32 Oz', 'quantity': 1.0, 'unit_price': 35.152, 'line_total': 35.152}, {'description': 'MILK OAT 12 0z OATLEY', 'quantity': 1.0, 'unit_price': 39.948, 'line_total': 39.0}, {'description': 'EGGS LIQUID 2 * 20 LB PAPETTIS', 'quantity': 1.0, 'unit_price': 100.35, 'line_total': 100.35}]}, {'invoice_number': '20077622', 'date': '8/6/2025', 'vendor': "Frank's QQuality Produce", 'total_amount': 79.11, 'line_items': [{'description': 'TOMATO, ROMA', 'quantity': 12.0, 'unit_price': 1.99, 'line_total': 23.88}, {'description': 'DILL BABY HERBS', 'quantity': 6.0, 'unit_price': 0.99, 'line_total': 5.94}, {'description': 'PARSLEY', 'quantity': 14.0, 'unit_price': 0.99, 'line_total': 13.86}, {'description': 'ITALIAN BN', 'quantity': 7.0, 'unit_price': 0.99, 'line_total': 6.93}, {'description': 'CUCUMBER', 'quantity': 1.0, 'unit_price': 11.0, 'line_total': 11.0}, {'description': 'ONION, GREEN', 'quantity': 1.0, 'unit_price': 10.0, 'line_total': 10.0}, {'description': 'FUEL SURCHARGE', 'quantity': 1.0, 'unit_price': 7.5, 'line_total': 7.5}]}, {'invoice_number': '20074433', 'date': '7/15/2025', 'vendor': "Frank's QQuality Produce", 'total_amount': 45.28, 'line_items': [{'description': 'CUCUMBER, XFANCY LG', 'quantity': 12.0, 'unit_price': 0.99, 'line_total': 11.88}, {'description': 'TOMATO, ROMA', 'quantity': 5.0, 'unit_price': 1.99, 'line_total': 9.95}, {'description': 'HERBS, DILL', 'quantity': 1.0, 'unit_price': 11.0, 'line_total': 11.0}, {'description': 'BABY ONION, ITALIAN', 'quantity': 5.0, 'unit_price': 0.99, 'line_total': 4.95}, {'description': 'FUEL SURCHARGE', 'quantity': 1.0, 'unit_price': 7.5, 'line_total': 7.5}]}, {'invoice_number': '2825', 'date': '7/28/2025', 'vendor': "Frank's QQuality Produce", 'total_amount': 78.12, 'line_items': [{'description': 'TOMATO, ROMA', 'quantity': 12.0, 'unit_price': 1.99, 'line_total': 23.88}, {'description': 'HERBS', 'quantity': 1.0, 'unit_price': 11.0, 'line_total': 11.0}, {'description': 'DILL BABY HERBS', 'quantity': 6.0, 'unit_price': 0.99, 'line_total': 5.94}, {'description': 'ITALIAN BN', 'quantity': 20.0, 'unit_price': 0.99, 'line_total': 19.8}, {'description': 'CUCUMBER, XFANCY', 'quantity': 1.0, 'unit_price': 10.0, 'line_total': 10.0}, {'description': 'LG EA ONION, GREEN', 'quantity': 1.0, 'unit_price': 7.5, 'line_total': 7.5}]}, {'invoice_number': '378094', 'date': '07/15/2025', 'vendor': 'Pacific Flood mporters INc', 'total_amount': 75.08, 'line_items': [{'description': 'SALT KOSHER COARSE DIAMOND CR X 3 LB', 'quantity': 1.0, 'unit_price': 75.076, 'line_total': 75.0}]}, {'invoice_number': '20078834', 'date': '8/14/2025', 'vendor': "Frank's QQuality Produce", 'total_amount': 53.35, 'line_items': [{'description': 'ONION, GREEN', 'quantity': 2.0, 'unit_price': 10.0, 'line_total': 20.0}, {'description': 'CUCUMBER, XFANCY LG', 'quantity': 15.0, 'unit_price': 0.99, 'line_total': 14.85}, {'description': 'HERBS, DILL BABY', 'quantity': 1.0, 'unit_price': 11.0, 'line_total': 11.0}, {'description': 'FUEL SURCHARGE', 'quantity': 1.0, 'unit_price': 7.5, 'line_total': 7.5}]}, {'invoice_number': '375298', 'date': '05/20/2025', 'vendor': 'Pacific Flood Importers Inc', 'total_amount': 357.8, 'line_items': [{'description': 'FLOUR POWER GRAINCRAFT', 'quantity': 8.0, 'unit_price': 24.063, 'line_total': 192.5}, {'description': 'SESAME SEEDS WHITE+ 4 * MARCA CROC', 'quantity': 1.0, 'unit_price': 80.25, 'line_total': 80.25}, {'description': 'MILK WHOLE GALLON RED CAP', 'quantity': 1.0, 'unit_price': 17.999, 'line_total': 18.0}, {'description': 'SUGAR GRANULATED CANE 25 LB CEH SUGAR', 'quantity': 1.0, 'unit_price': 29.147, 'line_total': 29.15}, {'description': 'HALF HALF QT MEDOSWEET', 'quantity': 2.0, 'unit_price': 2.637, 'line_total': 5.27}, {'description': 'GLOVE NITRILE MEDIUM 10', 'quantity': 1.0, 'unit_price': 29.771, 'line_total': 29.77}]}, {'invoice_number': '20065629', 'date': '5/13/2025', 'vendor': "Frank's QQuality Produce", 'total_amount': 109.26, 'line_items': [{'description': 'TOMATO, ROMA', 'quantity': 8.0, 'unit_price': 1.99, 'line_total': 15.92}, {'description': 'ONION, GREEN', 'quantity': 2.0, 'unit_price': 10.0, 'line_total': 20.0}, {'description': '12BN BAG HERBS, DILL', 'quantity': 1.0, 'unit_price': 11.0, 'line_total': 11.0}, {'description': 'BABY 10 ONION', 'quantity': 10.0, 'unit_price': 0.99, 'line_total': 9.9}, {'description': 'WHITE ONION', 'quantity': 6.0, 'unit_price': 0.99, 'line_total': 5.94}, {'description': 'ITALIAN RED # AVOCADO', 'quantity': 1.0, 'unit_price': 39.0, 'line_total': 39.0}, {'description': '1 LAYER FUEL SURCHARGE', 'quantity': 1.0, 'unit_price': 7.5, 'line_total': 7.5}]}, {'invoice_number': '20068140', 'date': '5/30/2025', 'vendor': "Frank's QQuality Produce", 'total_amount': 75.14, 'line_items': [{'description': 'TOMATO, ROMA', 'quantity': 10.0, 'unit_price': 1.99, 'line_total': 19.9}, {'description': 'CUCUMBER, XFANCY LG', 'quantity': 12.0, 'unit_price': 0.9, 'line_total': 10.8}, {'description': 'ONION; ITALIAN RED', 'quantity': 6.0, 'unit_price': 0.99, 'line_total': 5.94}, {'description': 'ONION, GREEN 12BN BAG', 'quantity': 2.0, 'unit_price': 10.0, 'line_total': 20.0}, {'description': 'HERBS, DILL BABY', 'quantity': 1.0, 'unit_price': 11.0, 'line_total': 11.0}, {'description': 'FUEL SURCHARGE', 'quantity': 1.0, 'unit_price': 7.5, 'line_total': 7.5}]}, {'invoice_number': '376173', 'date': '06/05/2025', 'vendor': 'Pacific Flood mporters INc', 'total_amount': 100.35, 'line_items': [{'description

In [ ]:
import json
from typing import List, Dict


def load_json(file_path: str) -> List[Dict]:
    with open(file_path, "r") as f:
        data = json.load(f)
    return data



def extract_invoice_data(raw_data: List[Dict]) -> List[Dict]:

    structured_data = []

    for invoice in raw_data:

        invoice_info = {
            "invoice_number": invoice.get("invoice_number"),
            "date": invoice.get("date"),
            "vendor_name": invoice.get("vendor"),
            "total_amount": invoice.get("total_amount"),
            "line_items": []
        }

        # Extract line items
        for item in invoice.get("line_items", []):
            line_item = {
                "description": item.get("description"),
                "quantity": item.get("quantity"),
                "unit_price": item.get("unit_price"),
                "line_total": item.get("line_total")
            }
            invoice_info["line_items"].append(line_item)

        structured_data.append(invoice_info)

    return structured_data



def save_output(data: List[Dict], output_path: str):
    with open(output_path, "w") as f:
        json.dump(data, f, indent=4)



if __name__ == "__main__":

    input_file = "/content/all_invoices.json"
    output_file = "structured_invoices.json"

    raw_json = load_json(input_file)

    cleaned_data = extract_invoice_data(raw_json)

    save_output(cleaned_data, output_file)

    print("✅ Extraction completed. Output saved.")

✅ Extraction completed. Output saved.

In [ ]:
with open("/content/structured_invoices.json", "r") as file:
    data = json.load(file)

In [ ]:
data

[{'invoice_number': '378793',
  'date': '07/29/2025',
  'vendor_name': 'Pacific Food Importers Inc.',
  'total_amount': 754.89,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT 50 LB',
    'quantity': 10.0001,
    'unit_price': 24.063,
    'line_total': 240.0},
   {'description': 'ONION MINCED MARCA CROC 4 * 4 .5 LB',
    'quantity': 1.0,
    'unit_price': 113.333,
    'line_total': 113.33},
   {'description': 'SESAME SEEDS MHITE+ MARCA CROC 4 LB',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'SALT KOSHER COARSE DIAMOND CR 3 LB',
    'quantity': 2.0,
    'unit_price': 75.076,
    'line_total': 150.15},
   {'description': 'GLOVE NITRILE XL 10 100 ct',
    'quantity': 1.0,
    'unit_price': 36.25,
    'line_total': 36.25},
   {'description': 'YEAST INSTANT RED LBL SAF 20',
    'quantity': 1.0,
    'unit_price': 130.0,
    'line_total': 130.0}]},
 {'invoice_number': '376172',
  'date': '06/05/2025',
  'vendor_name': 'Pacific Flood mporters INc',
  'total_amount': 133.42,
  'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20.000 LB',
    'quantity': 1.0,
    'unit_price': 133.418,
    'line_total': 133.0}]},
 {'invoice_number': '375991',
  'date': '06/03/2025',
  'vendor_name': 'Pacific Flood Importers Inc',
  'total_amount': 491.83,
  'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'FLOUR A/P UNBLEACHED GRAINCRAFT',
    'quantity': 1.0,
    'unit_price': 21.0,
    'line_total': 21.0},
   {'description': 'FLOUR MEDIUM RYE',
    'quantity': 1.0,
    'unit_price': 42.8,
    'line_total': 42.8},
   {'description': 'FLOUR MEDIUM RYE',
    'quantity': 1.0,
    'unit_price': 42.8,
    'line_total': 42.8},
   {'description': 'CORNMEAL YELLOH FINE** * 25 LB',
    'quantity': 1.0,
    'unit_price': 25.86,
    'line_total': 25.86},
   {'description': 'SALT KOSHER COARSE DIAMOND CR',
    'quantity': 9.0,
    'unit_price': 7.962,
    'line_total': 71.66},
   {'description': 'GLOVE NITRILE LARGE 10 X 100',
    'quantity': 1.0,
    'unit_price': 29.77,
    'line_total': 29.77},
   {'description': 'EGGS LIQUID PAPETTIS',
    'quantity': 1.0,
    'unit_price': 50.18,
    'line_total': 50.18}]},
 {'invoice_number': '20078834',
  'date': '8/14/2025',
  'vendor_name': "Frank's QQuality Produce",
  'total_amount': 53.35,
  'line_items': [{'description': 'ONION, GREEN',
    'quantity': 2.0,
    'unit_price': 10.0,
    'line_total': 20.0},
   {'description': 'CUCUMBER, XFANCY LG',
    'quantity': 15.0,
    'unit_price': 0.99,
    'line_total': 14.85},
   {'description': 'HERBS, DILL BABY',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '378483',
  'date': '07/22/2025',
  'vendor_name': 'Pacific Flood mporters INc',
  'total_amount': 576.63,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT LB',
    'quantity': 10.0001,
    'unit_price': 24.063,
    'line_total': 240.0},
   {'description': 'MALT POWDER DIASTATIC+ RED STAR JALAPENO SLICED #10 SAVOR LB',
    'quantity': 1.0,
    'unit_price': 116.848,
    'line_total': 116.85},
   {'description': '45.000 LB',
    'quantity': 1.0,
    'unit_price': 329.0,
    'line_total': 51.33},
   {'description': 'GLOVE NITRILE MEDIUM',
    'quantity': 1.0,
    'unit_price': 29.78,
    'line_total': 29.78},
   {'description': 'EGGS LIQUID PAPETTIS X 20 LB',
    'quantity': 1.0,
    'unit_price': 95.225,
    'line_total': 95.23}]},
 {'invoice_number': '20077622',
  'date': '8/6/2025',
  'vendor_name': "Frank's QQuality Produce",
  'total_amount': 79.11,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 12.0,
    'unit_price': 1.99,
    'line_total': 23.88},
   {'description': 'HERBS, DILL BABY HERBS, PARSLEY, ITALIAN',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'CUCUMBER, XFANCY',
    'quantity': 6.0,
    'unit_price': 0.99,
    'line_total': 5.94},
   {'description': 'ONION, GREEN',
    'quantity': 14.0,
    'unit_price': 0.99,
    'line_total': 13.86},
   {'description': 'ONION, ITALIAN RED',
    'quantity': 1.0,
    'unit_price': 10.0,
    'line_total': 10.0},
   {'description': 'BAG ONION, ITALIAN RED',
    'quantity': 7.0,
    'unit_price': 0.99,
    'line_total': 6.93},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5},
   {'description': 'Sales Tax',
    'quantity': 1.0,
    'unit_price': 10.25,
    'line_total': 0.0}]},
 {'invoice_number': '376739',
  'date': '06/17/2025',
  'vendor_name': 'Pacific Food Importers Inc.',
  'total_amount': 385.06,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT 50 LB',
    'quantity': 10.0001,
    'unit_price': 240.0,
    'line_total': 2400.024},
   {'description': 'EGGS LIQUID PAPETTIS HALF HALF MEDOSWEET 20 LB',
    'quantity': 1.0,
    'unit_price': 100.35,
    'line_total': 100.35},
   {'description': 'QT 4.376 LB',
    'quantity': 2.0,
    'unit_price': 665.0,
    'line_total': 33.0},
   {'description': 'GLOVE NITRILE XL 10',
    'quantity': 1.0,
    'unit_price': 35.361,
    'line_total': 35.36}]},
 {'invoice_number': '375991',
  'date': '06/03/2025',
  'vendor_name': 'Pacific Food Importers Inc.',
  'total_amount': 491.83,
  'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'FLOUR A/P UNBLEACHED GRAINCRAFT 50 LB',
    'quantity': 1.0,
    'unit_price': 21.0,
    'line_total': 21.0},
   {'description': 'FLOUR MEDIUM RYE 50 LB',
    'quantity': 1.0,
    'unit_price': 42.8,
    'line_total': 42.8},
   {'description': 'CORNMEAL YELLOW FINE 25 LB',
    'quantity': 1.0,
    'unit_price': 25.861,
    'line_total': 25.86},
   {'description': 'YEAST FRESH 20 * 16 OZ RED STAR',
    'quantity': 1.0,
    'unit_price': 58.06,
    'line_total': 58.06},
   {'description': 'SALT KOSHER COARSE DIAMOND CR 9 * 3 LB',
    'quantity': 9.0,
    'unit_price': 71.658,
    'line_total': 71.66},
   {'description': 'GLOVE NITRILE LARGE 10 X 100',
    'quantity': 1.0,
    'unit_price': 29.774,
    'line_total': 29.77},
   {'description': 'EGGS LIQUID PAPETTIS 2 * 20 LB',
    'quantity': 2.0,
    'unit_price': 25.09,
    'line_total': 50.18}]},
 {'invoice_number': '376355',
  'date': '06/10/2025',
  'vendor_name': 'Pacific Food Importers Inc',
  'total_amount': 688.51,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT',
    'quantity': 12.0,
    'unit_price': 24.063,
    'line_total': 288.0},
   {'description': 'BG MALT POWDER DIASTATIC+ RED STAR 0o0 JALAPENO SLICED #10 SAVOR',
    'quantity': 1.0,
    'unit_price': 119.177,
    'line_total': 119.18},
   {'description': '45.000 LB',
    'quantity': 1.0,
    'unit_price': 51.329,
    'line_total': 51.33},
   {'description': 'MILK OAT 12 oz',
    'quantity': 3.0,
    'unit_price': 39.948,
    'line_total': 119.84},
   {'description': 'SESAME SEEDS WHITE+ 4 * 5 LB MARCA CROC',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'SUGAR GRANULATED CANE 25 LB',
    'quantity': 1.0,
    'unit_price': 29.147,
    'line_total': 29.15}]},
 {'invoice_number': '376172',
  'date': '06/05/2025',
  'vendor_name': 'Pacific Food Importers Inc.',
  'total_amount': 133.42,
  'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20.000 LB',
    'quantity': 1.0,
    'unit_price': 133.418,
    'line_total': 133.42}]},
 {'invoice_number': '378093',
  'date': '07/15/2025',
  'vendor_name': 'Pacific Food Importers Inc.',
  'total_amount': 522.75,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT 50 LB',
    'quantity': 12.0,
    'unit_price': 24.0,
    'line_total': 288.0},
   {'description': 'CORNMEAL YELLOW FINE 25 LB',
    'quantity': 1.0,
    'unit_price': 25.1,
    'line_total': 25.1},
   {'description': 'GLOVE NITRILE MEDIUM x 100',
    'quantity': 1.0,
    'unit_price': 29.78,
    'line_total': 29.78},
   {'description': 'SESAME SEEDS WHITE+ MARCA CROC LB',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'POPPY SEED MARCA CROC 5.5 LB',
    'quantity': 1.0,
    'unit_price': 96.0,
    'line_total': 96.0},
   {'description': 'EGGS LIQUID PAPETTIS 20 LB',
    'quantity': 2.0,
    'unit_price': 47.6125,
    'line_total': 95.225}]},
 {'invoice_number': '20076301',
  'date': '7/28/2025',
  'vendor_name': "Frank's QQuality Produce",
  'total_amount': 78.12,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 12.0,
    'unit_price': 1.99,
    'line_total': 23.88},
   {'description': 'CUCUMBER, XFANCY LG',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'DILL BABY HERBS',
    'quantity': 6.0,
    'unit_price': 0.99,
    'line_total': 5.94},
   {'description': 'PARSLEY, ITALIAN',
    'quantity': 20.0,
    'unit_price': 0.99,
    'line_total': 19.8},
   {'description': 'ONION, GREEN',
    'quantity': 1.0,
    'unit_price': 10.0,
    'line_total': 10.0},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '20066901',
  'date': '5/22/2025',
  'vendor_name': "Frank's QQuality Produce",
  'total_amount': 75.14,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 10.0,
    'unit_price': 1.99,
    'line_total': 19.9},
   {'description': 'CUCUMBER, XFANCY LG',
    'quantity': 12.0,
    'unit_price': 0.9,
    'line_total': 10.8},
   {'description': 'ONION, GREEN',
    'quantity': 2.0,
    'unit_price': 10.0,
    'line_total': 20.0},
   {'description': 'HERBS, DILL BABY',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'HERBS, PARSLEY, ITALIAN BN',
    'quantity': 6.0,
    'unit_price': 0.99,
    'line_total': 5.94},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '20075310',
  'date': '7/21/2025',
  'vendor_name': "Frank's QQuality Produce",
  'total_amount': 74.26,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 12.0,
    'unit_price': 1.99,
    'line_total': 23.88},
   {'description': 'HERBS, DILL BABY',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'CUCUMBER, XFANCY LG',
    'quantity': 12.0,
    'unit_price': 0.99,
    'line_total': 11.88},
   {'description': 'ONION, GREEN',
    'quantity': 2.0,
    'unit_price': 10.0,
    'line_total': 20.0},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5},
   {'description': 'Sales Tax',
    'quantity': 0.0,
    'unit_price': 10.25,
    'line_total': 0.0}]},
 {'invoice_number': '375704',
  'date': '05/28/2025',
  'vendor_name': 'Pacific Food Importers Inc',
  'total_amount': 551.21,
  'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'JALAPENO SLICED #10 SAVOR SUGAR BROWN 25 LB WHITESATIN',
    'quantity': 1.0,
    'unit_price': 51.329,
    'line_total': 51.33},
   {'description': '26 . 000 LB',
    'quantity': 1.0,
    'unit_price': 26.778,
    'line_total': 26.0},
   {'description': 'MILK OAT 12 OATLEY EGGS LIQUID PAPETTIS',
    'quantity': 2.0,
    'unit_price': 39.948,
    'line_total': 79.0},
   {'description': 'X 20 LB',
    'quantity': 2.0,
    'unit_price': 100.35,
    'line_total': 200.0}]},
 {'invoice_number': '376485',
  'date': '06/11/2025',
  'vendor_name': 'Pacific Flood mporters INc',
  'total_amount': 133.42,
  'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20.000 LB',
    'quantity': 1.0,
    'unit_price': 133.42,
    'line_total': 133.42}]},
 {'invoice_number': '374941',
  'date': '05/13/2025',
  'vendor_name': 'Pacific Flood mporters INc',
  'total_amount': 289.85,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT 50 LB',
    'quantity': 10.0001,
    'unit_price': 24.063,
    'line_total': 240.0},
   {'description': 'CURRANTS LB',
    'quantity': 1.0,
    'unit_price': 16.588,
    'line_total': 16.59},
   {'description': 'GLOVE NITRILE LARGE 10',
    'quantity': 1.0,
    'unit_price': 29.774,
    'line_total': 29.77}]},
 {'invoice_number': '376462',
  'date': '06/11/2025',
  'vendor_name': 'Pacific Food Importers Inc',
  'total_amount': -133.42,
  'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20 -20 . 000 LB',
    'quantity': 1.0,
    'unit_price': 133.418,
    'line_total': -133.0}]},
 {'invoice_number': '379549',
  'date': '08/12/2025',
  'vendor_name': 'Pacific Food Importers Inc',
  'total_amount': 432.62,
  'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT',
    'quantity': 10.0001,
    'unit_price': 24.063,
    'line_total': 240.0},
   {'description': 'ALMOND BARISTA BLEND 12 * 32 CALIFIA EGGS LIQUID X 20 LB PAPETTIS',
    'quantity': 1.0,
    'unit_price': 41.139,
    'line_total': 41.14},
   {'description': 'LIMONATA CANS SAN PELLEG X 11 02',
    'quantity': 1.0,
    'unit_price': 95.225,
    'line_total': 95.23}]},
 {'invoice_number': '376462',
  'date': '06/11/2025',
  'vendor_name': 'Pacific Food Importers Inc.',
  'total_amount': -133.42,
  'line_items': [{'description': 'YEAST INSTANT RED LBL SAF 20',
    'quantity': 1.0,
    'unit_price': 133.42,
    'line_total': -133.42}]},
 {'invoice_number': '376486',
  'date': '06/11/2025',
  'vendor_name': 'Pacific Flood mporters INc',
  'total_amount': -54.62,
  'line_items': [{'description': 'YEAST FRESH RED STAR 20 X 16 Oz',
    'quantity': 1.0,
    'unit_price': 54.62,
    'line_total': -54.0}]},
 {'invoice_number': '376355',
  'date': '06/10/2025',
  'vendor_name': 'Pacific Flood Importers Inc',
  'total_amount': 688.51,
  'line_items': [{'description': 'FLOUR POWER GRAINCRAFT',
    'quantity': 12.0,
    'unit_price': 24.063,
    'line_total': 288.0},
   {'description': 'MALT POWDER DIASTATIC+ RED STAR 0o0 JALAPENO SLICED #10 SAVOR',
    'quantity': 1.0,
    'unit_price': 119.177,
    'line_total': 119.18},
   {'description': 'MALT POWDER NON-DIASTATIC',
    'quantity': 1.0,
    'unit_price': 51.329,
    'line_total': 51.33},
   {'description': 'MILK OAT 12',
    'quantity': 3.0,
    'unit_price': 39.948,
    'line_total': 119.84},
   {'description': 'SESAME SEEDS WHITE+ 4 * 5 LB MARCA CROC',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'SUGAR GRANULATED CANE 25 LB',
    'quantity': 1.0,
    'unit_price': 29.147,
    'line_total': 29.15}]},
 {'invoice_number': '20075310',
  'date': '7/21/2025',
  'vendor_name': "Frank's QQuality Produce",
  'total_amount': 74.26,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 12.0,
    'unit_price': 1.99,
    'line_total': 23.88},
   {'description': 'HERBS, DILL BABY',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'CUCUMBER, XFANCY LG',
    'quantity': 12.0,
    'unit_price': 0.99,
    'line_total': 11.88},
   {'description': 'ONION, GREEN',
    'quantity': 2.0,
    'unit_price': 10.0,
    'line_total': 20.0},
   {'description': 'BAG FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5},
   {'description': 'Sales Tax',
    'quantity': 0.0,
    'unit_price': 0.0,
    'line_total': 0.0}]},
 {'invoice_number': '377101',
  'date': '06/24/2025',
  'vendor_name': 'Pacific Food Importers Inc.',
  'total_amount': 738.17,
  'line_items': [{'description': 'FLOUR POWER 50 LB GRAINCRAFT',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'PAN SPRAY PREHIUM 6 * 14 02 VEGALENE SALT KOSHER COARSE 9 * 3 LB DIAMOND CR',
    'quantity': 1.0,
    'unit_price': 34.038,
    'line_total': 34.0},
   {'description': '',
    'quantity': 1.0,
    'unit_price': 75.076,
    'line_total': 75.0},
   {'description': 'ONION MINCED 4 * 4.5 LB MARCA CROC GARLIC MINCED LB MARCA CROC',
    'quantity': 1.0,
    'unit_price': 104.0,
    'line_total': 104.0},
   {'description': '',
    'quantity': 1.0,
    'unit_price': 112.0,
    'line_total': 112.0},
   {'description': 'SESAME SEEDS WHITE+ 4 * 5 LB MARCA CROC',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'MILK ALMOND PACIFIC 12 * 32 Oz',
    'quantity': 1.0,
    'unit_price': 35.152,
    'line_total': 35.152},
   {'description': 'MILK OAT 12 0z OATLEY',
    'quantity': 1.0,
    'unit_price': 39.948,
    'line_total': 39.0},
   {'description': 'EGGS LIQUID 2 * 20 LB PAPETTIS',
    'quantity': 1.0,
    'unit_price': 100.35,
    'line_total': 100.35}]},
 {'invoice_number': '20077622',
  'date': '8/6/2025',
  'vendor_name': "Frank's QQuality Produce",
  'total_amount': 79.11,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 12.0,
    'unit_price': 1.99,
    'line_total': 23.88},
   {'description': 'DILL BABY HERBS',
    'quantity': 6.0,
    'unit_price': 0.99,
    'line_total': 5.94},
   {'description': 'PARSLEY',
    'quantity': 14.0,
    'unit_price': 0.99,
    'line_total': 13.86},
   {'description': 'ITALIAN BN',
    'quantity': 7.0,
    'unit_price': 0.99,
    'line_total': 6.93},
   {'description': 'CUCUMBER',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'ONION, GREEN',
    'quantity': 1.0,
    'unit_price': 10.0,
    'line_total': 10.0},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '20074433',
  'date': '7/15/2025',
  'vendor_name': "Frank's QQuality Produce",
  'total_amount': 45.28,
  'line_items': [{'description': 'CUCUMBER, XFANCY LG',
    'quantity': 12.0,
    'unit_price': 0.99,
    'line_total': 11.88},
   {'description': 'TOMATO, ROMA',
    'quantity': 5.0,
    'unit_price': 1.99,
    'line_total': 9.95},
   {'description': 'HERBS, DILL',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'BABY ONION, ITALIAN',
    'quantity': 5.0,
    'unit_price': 0.99,
    'line_total': 4.95},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '2825',
  'date': '7/28/2025',
  'vendor_name': "Frank's QQuality Produce",
  'total_amount': 78.12,
  'line_items': [{'description': 'TOMATO, ROMA',
    'quantity': 12.0,
    'unit_price': 1.99,
    'line_total': 23.88},
   {'description': 'HERBS',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'DILL BABY HERBS',
    'quantity': 6.0,
    'unit_price': 0.99,
    'line_total': 5.94},
   {'description': 'ITALIAN BN',
    'quantity': 20.0,
    'unit_price': 0.99,
    'line_total': 19.8},
   {'description': 'CUCUMBER, XFANCY',
    'quantity': 1.0,
    'unit_price': 10.0,
    'line_total': 10.0},
   {'description': 'LG EA ONION, GREEN',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '378094',
  'date': '07/15/2025',
  'vendor_name': 'Pacific Flood mporters INc',
  'total_amount': 75.08,
  'line_items': [{'description': 'SALT KOSHER COARSE DIAMOND CR X 3 LB',
    'quantity': 1.0,
    'unit_price': 75.076,
    'line_total': 75.0}]},
 {'invoice_number': '20078834',
  'date': '8/14/2025',
  'vendor_name': "Frank's QQuality Produce",
  'total_amount': 53.35,
  'line_items': [{'description': 'ONION, GREEN',
    'quantity': 2.0,
    'unit_price': 10.0,
    'line_total': 20.0},
   {'description': 'CUCUMBER, XFANCY LG',
    'quantity': 15.0,
    'unit_price': 0.99,
    'line_total': 14.85},
   {'description': 'HERBS, DILL BABY',
    'quantity': 1.0,
    'unit_price': 11.0,
    'line_total': 11.0},
   {'description': 'FUEL SURCHARGE',
    'quantity': 1.0,
    'unit_price': 7.5,
    'line_total': 7.5}]},
 {'invoice_number': '375298',
  'date': '05/20/2025',

In [ ]:
invoice_rows = []

for inv in data:
    invoice_rows.append({
        "invoice_number": inv.get("invoice_number"),
        "date": inv.get("date"),
        "vendor_name": inv.get("vendor_name"),
        "total_amount": inv.get("total_amount")
    })

invoice_df = pd.DataFrame(invoice_rows)



line_item_rows = []

for inv in data:
    invoice_number = inv.get("invoice_number")

    for item in inv.get("line_items", []):
        line_item_rows.append({
            "invoice_number": invoice_number,   # 🔗 foreign key
            "description": item.get("description"),
            "quantity": item.get("quantity"),
            "unit_price": item.get("unit_price"),
            "line_total": item.get("line_total")
        })

line_items_df = pd.DataFrame(line_item_rows)

In [ ]:
invoice_df

   invoice_number        date                  vendor_name  total_amount
0          378793  07/29/2025  Pacific Food Importers Inc.        754.89
1          376172  06/05/2025   Pacific Flood mporters INc        133.42
2          375991  06/03/2025  Pacific Flood Importers Inc        491.83
3        20078834   8/14/2025     Frank's QQuality Produce         53.35
4          378483  07/22/2025   Pacific Flood mporters INc        576.63
5        20077622    8/6/2025     Frank's QQuality Produce         79.11
6          376739  06/17/2025  Pacific Food Importers Inc.        385.06
7          375991  06/03/2025  Pacific Food Importers Inc.        491.83
8          376355  06/10/2025   Pacific Food Importers Inc        688.51
9          376172  06/05/2025  Pacific Food Importers Inc.        133.42
10         378093  07/15/2025  Pacific Food Importers Inc.        522.75
11       20076301   7/28/2025     Frank's QQuality Produce         78.12
12       20066901   5/22/2025     Frank's QQuality Produce         75.14
13       20075310   7/21/2025     Frank's QQuality Produce         74.26
14         375704  05/28/2025   Pacific Food Importers Inc        551.21
15         376485  06/11/2025   Pacific Flood mporters INc        133.42
16         374941  05/13/2025   Pacific Flood mporters INc        289.85
17         376462  06/11/2025   Pacific Food Importers Inc       -133.42
18         379549  08/12/2025   Pacific Food Importers Inc        432.62
19         376462  06/11/2025  Pacific Food Importers Inc.       -133.42
20         376486  06/11/2025   Pacific Flood mporters INc        -54.62
21         376355  06/10/2025  Pacific Flood Importers Inc        688.51
22       20075310   7/21/2025     Frank's QQuality Produce         74.26
23         377101  06/24/2025  Pacific Food Importers Inc.        738.17
24       20077622    8/6/2025     Frank's QQuality Produce         79.11
25       20074433   7/15/2025     Frank's QQuality Produce         45.28
26           2825   7/28/2025     Frank's QQuality Produce         78.12
27         378094  07/15/2025   Pacific Flood mporters INc         75.08
28       20078834   8/14/2025     Frank's QQuality Produce         53.35
29         375298  05/20/2025  Pacific Flood Importers Inc        357.80
30       20065629   5/13/2025     Frank's QQuality Produce        109.26
31       20068140   5/30/2025     Frank's QQuality Produce         75.14
32         376173  06/05/2025   Pacific Flood mporters INc        100.35
33         376173  06/05/2025  Pacific Food Importers Inc.        100.35
34         378262  07/17/2025   Pacific Flood mporters INc         95.23
35       20074433   7/15/2025     Frank's QQuality Produce         45.28
36         376485  06/11/2025   Pacific Flood mporters INc        133.42
37         379183  08/05/2025  Pacific Food Importers Inc.        596.94
38         377184  06/25/2025   Pacific Flood mporters INc         41.14
39       20072265   6/27/2025     Frank's QQuality Produce         63.34
40         378206  07/16/2025   Pacific Flood mporters INc         95.23
41         377765  07/08/2025  Pacific Food Importers Inc.        557.38
42         376063  06/04/2025   Pacific Flood mporters INc         35.00
43       20072898    7/3/2025     Frank's QQuality Produce         82.09
44         376063  06/04/2025  Pacific Flood Importers Inc         35.00
45         376486  06/11/2025  Pacific Food Importers Inc.        -54.62
46       20068978    6/5/2025     Frank's QQuality Produce         90.12
47       20071084   6/20/2025     Frank's QQuality Produce         79.12

In [ ]:
line_items_df

,invoice_number,description,quantity,unit_price,line_total
0,378793,FLOUR POWER GRAINCRAFT 50 LB,10.0001,24.063,240.00
1,378793,ONION MINCED MARCA CROC 4 * 4 .5 LB,1.0000,113.333,113.33
2,378793,SESAME SEEDS MHITE+ MARCA CROC 4 LB,1.0000,80.250,80.25
3,378793,SALT KOSHER COARSE DIAMOND CR 3 LB,2.0000,75.076,150.15
4,378793,GLOVE NITRILE XL 10 100 ct,1.0000,36.250,36.25
...,...,...,...,...,...
200,20071084,"CUCUMBER, XFANCY LG EA",12.0000,0.900,10.80
201,20071084,"ONION; ITALIAN RED # ONION, GREEN",6.0000,0.990,5.94
202,20071084,12BN BAG HERBS,2.0000,10.000,20.00
203,20071084,DILL BABY,1.0000,11.000,11.00
204,20071084,FUEL SURCHARGE,1.0000,7.500,7.50

In [ ]:
invoice_df.to_csv("Invoices_df.csv",index=False)

In [ ]:
line_items_df.to_csv("line_items_df.csv",index=False)

In [ ]:
merged_invoices = pd.merge(line_items_df, invoice_df, on="invoice_number")

In [ ]:
merged_invoices

,invoice_number,description,quantity,unit_price,line_total,date,vendor_name,total_amount
0,378793,FLOUR POWER GRAINCRAFT 50 LB,10.0001,24.063,240.00,07/29/2025,Pacific Food Importers Inc.,754.89
1,378793,ONION MINCED MARCA CROC 4 * 4 .5 LB,1.0000,113.333,113.33,07/29/2025,Pacific Food Importers Inc.,754.89
2,378793,SESAME SEEDS MHITE+ MARCA CROC 4 LB,1.0000,80.250,80.25,07/29/2025,Pacific Food Importers Inc.,754.89
3,378793,SALT KOSHER COARSE DIAMOND CR 3 LB,2.0000,75.076,150.15,07/29/2025,Pacific Food Importers Inc.,754.89
4,378793,GLOVE NITRILE XL 10 100 ct,1.0000,36.250,36.25,07/29/2025,Pacific Food Importers Inc.,754.89
...,...,...,...,...,...,...,...,...
285,20071084,"CUCUMBER, XFANCY LG EA",12.0000,0.900,10.80,6/20/2025,Frank's QQuality Produce,79.12
286,20071084,"ONION; ITALIAN RED # ONION, GREEN",6.0000,0.990,5.94,6/20/2025,Frank's QQuality Produce,79.12
287,20071084,12BN BAG HERBS,2.0000,10.000,20.00,6/20/2025,Frank's QQuality Produce,79.12
288,20071084,DILL BABY,1.0000,11.000,11.00,6/20/2025,Frank's QQuality Produce,79.12
289,20071084,FUEL SURCHARGE,1.0000,7.500,7.50,6/20/2025,Frank's QQuality Produce,79.12

In [ ]:
merged_invoices.to_csv("full_Invoices.csv", index=False)