In [2]:
# %%capture
# !pip install pymupdf pandas openai tqdm
# !pip install -U google-api-python-client google-auth-httplib2 google-auth-oauthlib
# !pip install easyocr pdf2image pypdf
# !pip install gdown
# !apt-get install -y poppler-utils

In [1]:
import gdown
import os

# 1. Google Drive link to download invoices
drive_url = "Your Drive URL"

# 2. Define the local folder name
output_folder = "invoices"

# 3. Create the folder if it doesn't already exist
if not os.path.exists(output_folder):
    os.makedirs(output_folder)
    print(f"Created directory: {output_folder}")

# 4. Download the contents into the 'invoices'
gdown.download_folder(drive_url, output=output_folder, quiet=False, use_cookies=False)

Created directory: invoices

Retrieving folder contents

Processing file 1L6i3ZD3ARcmm8LjhFl_1qqksSeL3ifng Copy of ARPFIINVOEBTCHLASER (1).pdf
Processing file 1-ZnLgZ1nBrgIgT9oFyNdykquEgZZLukR Copy of ARPFIINVOEBTCHLASER (2).pdf
Processing file 1ZmRdVXqvb-tse4pc8MUKfTla5WZnAcCL Copy of ARPFIINVOEBTCHLASER (3).pdf
Processing file 14Jp8599xbUqOCGbKnVQPOigTMm0L1TBR Copy of ARPFIINVOEBTCHLASER (4).pdf
Processing file 1TwNhSTt6HjtWkr07tLWTWbvL-1QQm8eY Copy of ARPFIINVOEBTCHLASER (5).pdf
Processing file 1BntRm9_iLlUBRMXcNkWgfenIi0ZwkuTa Copy of ARPFIINVOEBTCHLASER (6).pdf
Processing file 1XN_4bokyPtuXCOKua9chg6IDuk7uqnQx Copy of ARPFIINVOEBTCHLASER (7).pdf
Processing file 1-GduiZQVYwTvCvce67bqts2YEzBwb-FH Copy of ARPFIINVOEBTCHLASER (8).pdf
Processing file 1inbal8MhzQ3e2qgUQvaIHJjvPLdbMoum Copy of ARPFIINVOEBTCHLASER (9).pdf
Processing file 1GC21wGevl169oMZG5E3H8KRTQ0SP39o5 Copy of ARPFIINVOEBTCHLASER (10).pdf
Processing file 1ZxgDDwtf_JwGRdTUEgY5A5gI6v-eq44_ Copy of ARPFIINVOEBTCHLASER (11).pdf
Processing file 1Z1MhINKP0XKPsfeMiQTWclXBnPjYCgOS Copy of ARPFIINVOEBTCHLASER (12).pdf
Processing file 1jdS3vjvWU0w62w3PP5q71yuG84MMl0Yk Copy of ARPFIINVOEBTCHLASER (13).pdf
Processing file 1GqhsQqnJVVb_Gvj86NAai_FxKWhJVbW3 Copy of ARPFIINVOEBTCHLASER (14).pdf
Processing file 1NuUcFGqHFM8DI7T6rEVvUm-MXd-Z7ubJ Copy of ARPFIINVOEBTCHLASER.pdf
Processing file 1GzGhUZoBK4LZwihS0FmG5sMsHJhwSFxF Copy of Inv_20065629_from_Franks_Quality_Produce_18417572_22492.pdf
Processing file 1XbIQzwUrFMr50C12SkT7XhovVPtk9yvT Copy of Inv_20066901_from_Franks_Quality_Produce_18471648_18416.pdf
Processing file 17CQ5rMCh5P1NvsK1Qn1bY6Hl2HZtMHpS Copy of Inv_20068140_from_Franks_Quality_Produce_18529019_11828.pdf
Processing file 1eUeSIRQTY9yi8pIQECSvolZGGfZcPdPj Copy of Inv_20068978_from_Franks_Quality_Produce_18559799_11828.pdf
Processing file 1DxPCYsl27p4rV8ArcyE5Xcxx7LMB74WW Copy of Inv_20071084_from_Franks_Quality_Produce_18665028_7884.pdf
Processing file 1-gfkMfK8Fh9pYqQeA4s97zsCIcssqJac Copy of Inv_20072265_from_Franks_Quality_Produce_18697771_15688.pdf
Processing file 1iMmajISklDyiVbmW10Dcwpxu86kPpBFq Copy of Inv_20072898_from_Franks_Quality_Produce_18731344_15688.pdf
Processing file 1W-PSy3p9xakWObf_mlHUTjxVp--x0T5z Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408 (1).pdf
Processing file 1jFe4IdZhyDDIRWCGdzYw9CuJarj4Fv_H Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408.pdf
Processing file 1jm1TQNOCm_sunyziyTt-RLdz7_a2kQjY Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952 (1).pdf
Processing file 1_RzGpU7pNPWMod3usZnOFRjTpAxvGKIV Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952.pdf
Processing file 1FD3dR6wozZTTuqilwBZZ2YAUoh2rqVw2 Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748 (1).pdf
Processing file 1pgS2CG5re5PqSA-hh5YOvDntv9FGqMto Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748.pdf
Processing file 1DhMbHD2VGlSy567mewL1mBHvkQtNv7KX Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596 (1).pdf
Processing file 1NGcnqS5zAnMPNUdTLQ7ZsDVpMG7KLVf6 Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596.pdf
Processing file 1S-fzpa0nfkZlpL3Ly6CbPRSADrKh8a8E Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132 (1).pdf
Processing file 1VDH6Vmn_Q91o9AEBZhorhK5jggfu8PIY Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132.pdf

Retrieving folder contents completed
Building directory structure
Building directory structure completed
Downloading...
From: https://drive.google.com/uc?id=1L6i3ZD3ARcmm8LjhFl_1qqksSeL3ifng
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (1).pdf
100%|██████████| 39.4k/39.4k [00:00<00:00, 48.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-ZnLgZ1nBrgIgT9oFyNdykquEgZZLukR
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (2).pdf
100%|██████████| 39.3k/39.3k [00:00<00:00, 49.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ZmRdVXqvb-tse4pc8MUKfTla5WZnAcCL
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (3).pdf
100%|██████████| 39.3k/39.3k [00:00<00:00, 20.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=14Jp8599xbUqOCGbKnVQPOigTMm0L1TBR
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (4).pdf
100%|██████████| 46.5k/46.5k [00:00<00:00, 25.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1TwNhSTt6HjtWkr07tLWTWbvL-1QQm8eY
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (5).pdf
100%|██████████| 39.2k/39.2k [00:00<00:00, 61.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1BntRm9_iLlUBRMXcNkWgfenIi0ZwkuTa
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (6).pdf
100%|██████████| 41.9k/41.9k [00:00<00:00, 19.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1XN_4bokyPtuXCOKua9chg6IDuk7uqnQx
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (7).pdf
100%|██████████| 39.1k/39.1k [00:00<00:00, 51.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-GduiZQVYwTvCvce67bqts2YEzBwb-FH
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (8).pdf
100%|██████████| 46.6k/46.6k [00:00<00:00, 30.0MB/s]
Downloading...
From: https://drive.google.com/uc?id=1inbal8MhzQ3e2qgUQvaIHJjvPLdbMoum
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (9).pdf
100%|██████████| 46.6k/46.6k [00:00<00:00, 28.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1GC21wGevl169oMZG5E3H8KRTQ0SP39o5
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (10).pdf
100%|██████████| 46.7k/46.7k [00:00<00:00, 58.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1ZxgDDwtf_JwGRdTUEgY5A5gI6v-eq44_
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (11).pdf
100%|██████████| 46.7k/46.7k [00:00<00:00, 17.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1Z1MhINKP0XKPsfeMiQTWclXBnPjYCgOS
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (12).pdf
100%|██████████| 39.2k/39.2k [00:00<00:00, 19.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=1jdS3vjvWU0w62w3PP5q71yuG84MMl0Yk
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (13).pdf
100%|██████████| 39.3k/39.3k [00:00<00:00, 24.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1GqhsQqnJVVb_Gvj86NAai_FxKWhJVbW3
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER (14).pdf
100%|██████████| 39.0k/39.0k [00:00<00:00, 18.9MB/s]
Downloading...
From: https://drive.google.com/uc?id=1NuUcFGqHFM8DI7T6rEVvUm-MXd-Z7ubJ
To: /content/invoices/Copy of ARPFIINVOEBTCHLASER.pdf
100%|██████████| 39.1k/39.1k [00:00<00:00, 49.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1GzGhUZoBK4LZwihS0FmG5sMsHJhwSFxF
To: /content/invoices/Copy of Inv_20065629_from_Franks_Quality_Produce_18417572_22492.pdf
100%|██████████| 73.4k/73.4k [00:00<00:00, 61.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1XbIQzwUrFMr50C12SkT7XhovVPtk9yvT
To: /content/invoices/Copy of Inv_20066901_from_Franks_Quality_Produce_18471648_18416.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 29.8MB/s]
Downloading...
From: https://drive.google.com/uc?id=17CQ5rMCh5P1NvsK1Qn1bY6Hl2HZtMHpS
To: /content/invoices/Copy of Inv_20068140_from_Franks_Quality_Produce_18529019_11828.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 34.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1eUeSIRQTY9yi8pIQECSvolZGGfZcPdPj
To: /content/invoices/Copy of Inv_20068978_from_Franks_Quality_Produce_18559799_11828.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 58.6MB/s]
Downloading...
From: https://drive.google.com/uc?id=1DxPCYsl27p4rV8ArcyE5Xcxx7LMB74WW
To: /content/invoices/Copy of Inv_20071084_from_Franks_Quality_Produce_18665028_7884.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 45.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1-gfkMfK8Fh9pYqQeA4s97zsCIcssqJac
To: /content/invoices/Copy of Inv_20072265_from_Franks_Quality_Produce_18697771_15688.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 23.5MB/s]
Downloading...
From: https://drive.google.com/uc?id=1iMmajISklDyiVbmW10Dcwpxu86kPpBFq
To: /content/invoices/Copy of Inv_20072898_from_Franks_Quality_Produce_18731344_15688.pdf
100%|██████████| 73.4k/73.4k [00:00<00:00, 20.2MB/s]
Downloading...
From: https://drive.google.com/uc?id=1W-PSy3p9xakWObf_mlHUTjxVp--x0T5z
To: /content/invoices/Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408 (1).pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 64.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1jFe4IdZhyDDIRWCGdzYw9CuJarj4Fv_H
To: /content/invoices/Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 49.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1jm1TQNOCm_sunyziyTt-RLdz7_a2kQjY
To: /content/invoices/Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952 (1).pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 48.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1_RzGpU7pNPWMod3usZnOFRjTpAxvGKIV
To: /content/invoices/Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 24.3MB/s]
Downloading...
From: https://drive.google.com/uc?id=1FD3dR6wozZTTuqilwBZZ2YAUoh2rqVw2
To: /content/invoices/Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748 (1).pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 63.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1pgS2CG5re5PqSA-hh5YOvDntv9FGqMto
To: /content/invoices/Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748.pdf
100%|██████████| 73.3k/73.3k [00:00<00:00, 24.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1DhMbHD2VGlSy567mewL1mBHvkQtNv7KX
To: /content/invoices/Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596 (1).pdf
100%|██████████| 73.5k/73.5k [00:00<00:00, 63.1MB/s]
Downloading...
From: https://drive.google.com/uc?id=1NGcnqS5zAnMPNUdTLQ7ZsDVpMG7KLVf6
To: /content/invoices/Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596.pdf
100%|██████████| 73.5k/73.5k [00:00<00:00, 18.4MB/s]
Downloading...
From: https://drive.google.com/uc?id=1S-fzpa0nfkZlpL3Ly6CbPRSADrKh8a8E
To: /content/invoices/Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132 (1).pdf
100%|██████████| 73.1k/73.1k [00:00<00:00, 55.7MB/s]
Downloading...
From: https://drive.google.com/uc?id=1VDH6Vmn_Q91o9AEBZhorhK5jggfu8PIY
To: /content/invoices/Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132.pdf
100%|██████████| 73.1k/73.1k [00:00<00:00, 62.7MB/s]
Download completed

['invoices/Copy of ARPFIINVOEBTCHLASER (1).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (2).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (3).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (4).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (5).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (6).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (7).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (8).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (9).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (10).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (11).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (12).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (13).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER (14).pdf',
 'invoices/Copy of ARPFIINVOEBTCHLASER.pdf',
 'invoices/Copy of Inv_20065629_from_Franks_Quality_Produce_18417572_22492.pdf',
 'invoices/Copy of Inv_20066901_from_Franks_Quality_Produce_18471648_18416.pdf',
 'invoices/Copy of Inv_20068140_from_Franks_Quality_Produce_18529019_11828.pdf',
 'invoices/Copy of Inv_20068978_from_Franks_Quality_Produce_18559799_11828.pdf',
 'invoices/Copy of Inv_20071084_from_Franks_Quality_Produce_18665028_7884.pdf',
 'invoices/Copy of Inv_20072265_from_Franks_Quality_Produce_18697771_15688.pdf',
 'invoices/Copy of Inv_20072898_from_Franks_Quality_Produce_18731344_15688.pdf',
 'invoices/Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408 (1).pdf',
 'invoices/Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408.pdf',
 'invoices/Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952 (1).pdf',
 'invoices/Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952.pdf',
 'invoices/Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748 (1).pdf',
 'invoices/Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748.pdf',
 'invoices/Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596 (1).pdf',
 'invoices/Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596.pdf',
 'invoices/Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132 (1).pdf',
 'invoices/Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132.pdf']

In [13]:
from pydantic import BaseModel
from typing import List

class LineItem(BaseModel):
    description: str
    quantity: float
    unit_price: float
    line_total: float


class Invoice(BaseModel):
    Invoice_Number: str
    Invoice_Date: str
    Vendor_Name: str
    Ship_To: str
    Cust_Id: str
    Order_Date: str
    Invoice_Total: float
    items: List[LineItem]

In [4]:
!pip install pdfplumber pydantic

Collecting pdfplumber
  Downloading pdfplumber-0.11.9-py3-none-any.whl.metadata (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.6/43.6 kB 1.9 MB/s eta 0:00:00
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (2.12.3)
Collecting pdfminer.six==20251230 (from pdfplumber)
  Downloading pdfminer_six-20251230-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: Pillow>=9.1 in /usr/local/lib/python3.12/dist-packages (from pdfplumber) (11.3.0)
Collecting pypdfium2>=4.18.0 (from pdfplumber)
  Downloading pypdfium2-5.5.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (68 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 68.1/68.1 kB 5.0 MB/s eta 0:00:00
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (3.4.4)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.12/dist-packages (from pdfminer.six==20251230->pdfplumber) (43.0.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic) (0.4.2)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.12/dist-packages (from cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (2.0.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.12/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six==20251230->pdfplumber) (3.0)
Downloading pdfplumber-0.11.9-py3-none-any.whl (60 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 60.0/60.0 kB 4.3 MB/s eta 0:00:00
Downloading pdfminer_six-20251230-py3-none-any.whl (6.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 6.6/6.6 MB 64.9 MB/s eta 0:00:00
Downloading pypdfium2-5.5.0-py3-none-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.0 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 91.5 MB/s eta 0:00:00
Installing collected packages: pypdfium2, pdfminer.six, pdfplumber
Successfully installed pdfminer.six-20251230 pdfplumber-0.11.9 pypdfium2-5.5.0

In [5]:
import pdfplumber
import re


def extract_text_from_pdf(pdf_path):

    text = ""

    with pdfplumber.open(pdf_path) as pdf:
        for page in pdf.pages:
            page_text = page.extract_text()
            if page_text:
                text += page_text + "\n"

    return text

In [6]:
def extract_invoice_fields(text):

    header_match = re.search(
        r'NET\s+\d+\s+DAYS\s+(\d+)\s+(\d+)\s+(\d{2}/\d{2}/\d{4})',
        text
    )

    invoice_match = re.search(
        r'INVOICE DATE\s*\n(\d{2}/\d{2}/\d{4})',
        text
    )

    total_match = re.search(
        r'INVOICE TOTAL.*?\$?\s*([\d]+\.\d+)',
        text,
        re.S
    )

    return {
        "Invoice_Number": header_match.group(1) if header_match else "",
        "Cust_Id": header_match.group(2) if header_match else "",
        "Order_Date": header_match.group(3) if header_match else "",
        "Invoice_Date": invoice_match.group(1) if invoice_match else "",
        "Vendor_Name": "Pacific Food Importers",
        "Ship_To": "Seattle WA",
        "Invoice_Total": float(total_match.group(1)) if total_match else 0.0
    }

In [7]:
def extract_items(text):

    items = []

    lines = text.split("\n")

    for line in lines:

        parts = line.split()

        if len(parts) > 8 and parts[0].isdigit():

            try:
                quantity = float(parts[1])
                unit_price = float(parts[-3])
                line_total = float(parts[-1])

                description = " ".join(parts[4:-4])

                item = LineItem(
                    description=description,
                    quantity=quantity,
                    unit_price=unit_price,
                    line_total=line_total
                )

                items.append(item)

            except:
                pass

    return items

In [8]:
import os
import json

pdf_folder = "/content/invoices"   # folder containing PDFs

all_invoices = []

for file in os.listdir(pdf_folder):

    if file.endswith(".pdf"):

        pdf_path = os.path.join(pdf_folder, file)

        print("Processing:", file)

        text = extract_text_from_pdf(pdf_path)

        invoice_data = extract_invoice_fields(text)

        items = extract_items(text)

        invoice = Invoice(
            **invoice_data,
            items=items
        )

        all_invoices.append(invoice.model_dump())

Processing: Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408 (1).pdf
Processing: Copy of ARPFIINVOEBTCHLASER (14).pdf
Processing: Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596.pdf
Processing: Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132 (1).pdf
Processing: Copy of ARPFIINVOEBTCHLASER.pdf
Processing: Copy of Inv_20066901_from_Franks_Quality_Produce_18471648_18416.pdf
Processing: Copy of ARPFIINVOEBTCHLASER (5).pdf
Processing: Copy of Inv_20078834_from_Franks_Quality_Produce_18994615_32132.pdf
Processing: Copy of Inv_20072265_from_Franks_Quality_Produce_18697771_15688.pdf
Processing: Copy of ARPFIINVOEBTCHLASER (4).pdf
Processing: Copy of Inv_20068978_from_Franks_Quality_Produce_18559799_11828.pdf
Processing: Copy of ARPFIINVOEBTCHLASER (1).pdf
Processing: Copy of Inv_20071084_from_Franks_Quality_Produce_18665028_7884.pdf
Processing: Copy of ARPFIINVOEBTCHLASER (11).pdf
Processing: Copy of ARPFIINVOEBTCHLASER (6).pdf
Processing: Copy of ARPFIINVOEBTCHLASER (7).pdf
Processing: Copy of Inv_20072898_from_Franks_Quality_Produce_18731344_15688.pdf
Processing: Copy of ARPFIINVOEBTCHLASER (3).pdf
Processing: Copy of Inv_20065629_from_Franks_Quality_Produce_18417572_22492.pdf
Processing: Copy of ARPFIINVOEBTCHLASER (2).pdf
Processing: Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952 (1).pdf
Processing: Copy of ARPFIINVOEBTCHLASER (10).pdf
Processing: Copy of ARPFIINVOEBTCHLASER (13).pdf
Processing: Copy of ARPFIINVOEBTCHLASER (9).pdf
Processing: Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748.pdf
Processing: Copy of Inv_20068140_from_Franks_Quality_Produce_18529019_11828.pdf
Processing: Copy of ARPFIINVOEBTCHLASER (8).pdf
Processing: Copy of Inv_20076301_from_Franks_Quality_Produce_18887473_13748 (1).pdf
Processing: Copy of ARPFIINVOEBTCHLASER (12).pdf
Processing: Copy of Inv_20075310_from_Franks_Quality_Produce_18842235_13952.pdf
Processing: Copy of Inv_20077622_from_Franks_Quality_Produce_18946409_7596 (1).pdf
Processing: Copy of Inv_20074433_from_Franks_Quality_Produce_18802791_20408.pdf

In [9]:
with open("invoices_output.json", "w") as f:
    json.dump(all_invoices, f, indent=2)

print("All invoices saved to invoices_output.json")

All invoices saved to invoices_output.json

In [10]:
all_invoices

[{'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '440912',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '05/12/2025',
  'Invoice_Total': 289.85,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 10.0,
    'unit_price': 24.063,
    'line_total': 240.63},
   {'description': 'NITRILE LARGE 10 x 100 s',
    'quantity': 1.0,
    'unit_price': 29.774,
    'line_total': 29.77}]},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '446026',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '08/11/2025',
  'Invoice_Total': 432.62,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 10.0,
    'unit_price': 24.063,
    'line_total': 240.63},
   {'description': 'BARISTA BLEND 12 X 32',
    'quantity': 1.0,
    'unit_price': 41.139,
    'line_total': 41.14},
   {'description': 'LIQUID 2 X 20 LB',
    'quantity': 1.0,
    'unit_price': 95.225,
    'line_total': 95.23},
   {'description': 'CANS 24 X 11 OZ',
    'quantity': 2.0,
    'unit_price': 27.81,
    'line_total': 55.62}]},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '444038',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '07/07/2025',
  'Invoice_Total': 557.38,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 10.0,
    'unit_price': 24.063,
    'line_total': 240.63},
   {'description': 'NITRILE XL 10 x 100 ct s',
    'quantity': 1.0,
    'unit_price': 35.383,
    'line_total': 35.38},
   {'description': 'EXTRA 12 X 454 GRM',
    'quantity': 1.0,
    'unit_price': 57.776,
    'line_total': 57.78},
   {'description': 'OAT 12 X 32 OZ',
    'quantity': 3.0,
    'unit_price': 39.948,
    'line_total': 119.84},
   {'description': 'LIQUID 2 X 20 LB',
    'quantity': 1.0,
    'unit_price': 100.35,
    'line_total': 100.35}]},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '444434',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '07/14/2025',
  'Invoice_Total': 522.75,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 12.0,
    'unit_price': 24.063,
    'line_total': 288.76},
   {'description': 'YELLOW FINE 25 LB',
    'quantity': 1.0,
    'unit_price': 25.101,
    'line_total': 25.1},
   {'description': 'NITRILE MEDIUM 10 x 100 s',
    'quantity': 1.0,
    'unit_price': 29.783,
    'line_total': 29.78},
   {'description': 'SEEDS WHITE+ 4 X 5 LB',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'SEED 4 X 5.5 LB',
    'quantity': 1.0,
    'unit_price': 96.0,
    'line_total': 96.0},
   {'description': 'KOSHER COARSE 9 X 3 LB',
    'quantity': 1.0,
    'unit_price': 75.076,
    'line_total': 75.08},
   {'description': 'LIQUID 2 X 20 LB',
    'quantity': 2.0,
    'unit_price': 95.225,
    'line_total': 95.23}]},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '445630',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '08/04/2025',
  'Invoice_Total': 596.94,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'SEEDS WHITE+ 4 X 5 LB',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'SLICED 6 #10',
    'quantity': 1.0,
    'unit_price': 51.329,
    'line_total': 51.33},
   {'description': 'OAT 12 X 32 OZ',
    'quantity': 3.0,
    'unit_price': 39.948,
    'line_total': 119.84},
   {'description': 'GRANULATED CANE 25 LB',
    'quantity': 1.0,
    'unit_price': 28.587,
    'line_total': 28.59},
   {'description': 'LIQUID 2 X 20 LB',
    'quantity': 1.0,
    'unit_price': 95.225,
    'line_total': 95.23}]},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '442055',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '06/02/2025',
  'Invoice_Total': 491.83,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'A/P UNBLEACHED 50 LB',
    'quantity': 1.0,
    'unit_price': 21.582,
    'line_total': 21.58},
   {'description': 'MEDIUM RYE 50 LB',
    'quantity': 1.0,
    'unit_price': 42.8,
    'line_total': 42.8},
   {'description': 'YELLOW FINE*** 25 LB',
    'quantity': 1.0,
    'unit_price': 25.861,
    'line_total': 25.86},
   {'description': 'FRESH + 20 X 16 OZ',
    'quantity': 1.0,
    'unit_price': 54.62,
    'line_total': 54.62},
   {'description': 'KOSHER COARSE 9 X 3 LB',
    'quantity': 1.0,
    'unit_price': 71.658,
    'line_total': 71.66},
   {'description': 'NITRILE LARGE 10 x 100 s',
    'quantity': 1.0,
    'unit_price': 29.774,
    'line_total': 29.77},
   {'description': 'LIQUID 2 X 20 LB',
    'quantity': 1.0,
    'unit_price': 100.35,
    'line_total': 50.18},
   {'description': 'INSTANT RED LBL SAF 20 X',
    'quantity': 1.0,
    'unit_price': 133.418,
    'line_total': 133.42}]},
 {'Invoice_Number': '443328',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '06/23/2025',
  'Invoice_Total': 738.17,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'SPRAY PREMIUM 6 X 14 OZ',
    'quantity': 1.0,
    'unit_price': 34.038,
    'line_total': 34.04},
   {'description': 'KOSHER COARSE 9 X 3 LB',
    'quantity': 1.0,
    'unit_price': 75.076,
    'line_total': 75.08},
   {'description': 'MINCED 4 X 4.5 LB',
    'quantity': 1.0,
    'unit_price': 104.0,
    'line_total': 104.0},
   {'description': 'MINCED 4 X 6 LB',
    'quantity': 1.0,
    'unit_price': 112.0,
    'line_total': 112.0},
   {'description': 'SEEDS WHITE+ 4 X 5 LB',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'OAT 12 X 32 OZ',
    'quantity': 1.0,
    'unit_price': 39.948,
    'line_total': 39.95},
   {'description': 'LIQUID 2 X 20 LB',
    'quantity': 1.0,
    'unit_price': 100.35,
    'line_total': 100.35},
   {'description': 'BARISTA BLEND 12 X 32',
    'quantity': 1.0,
    'unit_price': 41.139,
    'line_total': 41.14}]},
 {'Invoice_Number': '442951',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '06/16/2025',
  'Invoice_Total': 385.06,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 10.0,
    'unit_price': 24.063,
    'line_total': 240.63},
   {'description': 'LIQUID 2 X 20 LB',
    'quantity': 1.0,
    'unit_price': 100.35,
    'line_total': 100.35},
   {'description': 'NITRILE XL 10 x 100 ct s',
    'quantity': 1.0,
    'unit_price': 35.361,
    'line_total': 35.36}]},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '444831',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '07/21/2025',
  'Invoice_Total': 576.63,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 10.0,
    'unit_price': 24.063,
    'line_total': 240.63},
   {'description': 'POWDER DIASTATIC+ 50 LB',
    'quantity': 1.0,
    'unit_price': 116.848,
    'line_total': 116.85},
   {'description': 'SLICED 6 #10',
    'quantity': 1.0,
    'unit_price': 51.329,
    'line_total': 51.33},
   {'description': 'NITRILE MEDIUM 10 x 100 s',
    'quantity': 1.0,
    'unit_price': 29.78,
    'line_total': 29.78},
   {'description': 'LIQUID 2 X 20 LB',
    'quantity': 1.0,
    'unit_price': 95.225,
    'line_total': 95.23},
   {'description': 'OAT 12 X 32 OZ',
    'quantity': 1.0,
    'unit_price': 39.948,
    'line_total': 39.95}]},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '445193',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '07/28/2025',
  'Invoice_Total': 754.89,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 10.0,
    'unit_price': 24.063,
    'line_total': 240.63},
   {'description': 'MINCED 4 X 4.5 LB',
    'quantity': 1.0,
    'unit_price': 113.333,
    'line_total': 113.33},
   {'description': 'SEEDS WHITE+ 4 X 5 LB',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'KOSHER COARSE 9 X 3 LB',
    'quantity': 2.0,
    'unit_price': 75.076,
    'line_total': 150.15},
   {'description': 'NITRILE XL 10 x 100 ct s',
    'quantity': 1.0,
    'unit_price': 36.25,
    'line_total': 36.25},
   {'description': 'INSTANT RED LBL SAF 20 X',
    'quantity': 1.0,
    'unit_price': 130.797,
    'line_total': 130.8}]},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '442055',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '06/02/2025',
  'Invoice_Total': 491.83,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'A/P UNBLEACHED 50 LB',
    'quantity': 1.0,
    'unit_price': 21.582,
    'line_total': 21.58},
   {'description': 'MEDIUM RYE 50 LB',
    'quantity': 1.0,
    'unit_price': 42.8,
    'line_total': 42.8},
   {'description': 'YELLOW FINE*** 25 LB',
    'quantity': 1.0,
    'unit_price': 25.861,
    'line_total': 25.86},
   {'description': 'FRESH + 20 X 16 OZ',
    'quantity': 1.0,
    'unit_price': 54.62,
    'line_total': 54.62},
   {'description': 'KOSHER COARSE 9 X 3 LB',
    'quantity': 1.0,
    'unit_price': 71.658,
    'line_total': 71.66},
   {'description': 'NITRILE LARGE 10 x 100 s',
    'quantity': 1.0,
    'unit_price': 29.774,
    'line_total': 29.77},
   {'description': 'LIQUID 2 X 20 LB',
    'quantity': 1.0,
    'unit_price': 100.35,
    'line_total': 50.18},
   {'description': 'INSTANT RED LBL SAF 20 X',
    'quantity': 1.0,
    'unit_price': 133.418,
    'line_total': 133.42}]},
 {'Invoice_Number': '441300',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '05/19/2025',
  'Invoice_Total': 357.8,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'SEEDS WHITE+ 4 X 5 LB',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'WHOLE GALLON RED CAP 4',
    'quantity': 1.0,
    'unit_price': 17.999,
    'line_total': 18.0},
   {'description': 'GRANULATED CANE 25 LB',
    'quantity': 1.0,
    'unit_price': 29.147,
    'line_total': 29.15},
   {'description': 'NITRILE MEDIUM 10 x 100 s',
    'quantity': 1.0,
    'unit_price': 29.771,
    'line_total': 29.77}]},
 {'Invoice_Number': '442484',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '06/09/2025',
  'Invoice_Total': 688.51,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 12.0,
    'unit_price': 24.063,
    'line_total': 288.76},
   {'description': 'POWDER DIASTATIC+ 50 LB',
    'quantity': 1.0,
    'unit_price': 119.177,
    'line_total': 119.18},
   {'description': 'SLICED 6 #10',
    'quantity': 1.0,
    'unit_price': 51.329,
    'line_total': 51.33},
   {'description': 'OAT 12 X 32 OZ',
    'quantity': 3.0,
    'unit_price': 39.948,
    'line_total': 119.84},
   {'description': 'SEEDS WHITE+ 4 X 5 LB',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'GRANULATED CANE 25 LB',
    'quantity': 1.0,
    'unit_price': 29.147,
    'line_total': 29.15},
   {'description': 'INSTANT RED LBL SAF 20 X',
    'quantity': -1.0,
    'unit_price': 133.418,
    'line_total': -133.42},
   {'description': 'FRESH + 20 X 16 OZ',
    'quantity': -1.0,
    'unit_price': 54.62,
    'line_total': -54.62}]},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '442484',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '06/09/2025',
  'Invoice_Total': 688.51,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 12.0,
    'unit_price': 24.063,
    'line_total': 288.76},
   {'description': 'POWDER DIASTATIC+ 50 LB',
    'quantity': 1.0,
    'unit_price': 119.177,
    'line_total': 119.18},
   {'description': 'SLICED 6 #10',
    'quantity': 1.0,
    'unit_price': 51.329,
    'line_total': 51.33},
   {'description': 'OAT 12 X 32 OZ',
    'quantity': 3.0,
    'unit_price': 39.948,
    'line_total': 119.84},
   {'description': 'SEEDS WHITE+ 4 X 5 LB',
    'quantity': 1.0,
    'unit_price': 80.25,
    'line_total': 80.25},
   {'description': 'GRANULATED CANE 25 LB',
    'quantity': 1.0,
    'unit_price': 29.147,
    'line_total': 29.15},
   {'description': 'INSTANT RED LBL SAF 20 X',
    'quantity': -1.0,
    'unit_price': 133.418,
    'line_total': -133.42},
   {'description': 'FRESH + 20 X 16 OZ',
    'quantity': -1.0,
    'unit_price': 54.62,
    'line_total': -54.62}]},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '441766',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '05/27/2025',
  'Invoice_Total': 551.21,
  'items': [{'description': 'POWER 50 LB',
    'quantity': 8.0,
    'unit_price': 24.063,
    'line_total': 192.5},
   {'description': 'SLICED 6 #10',
    'quantity': 1.0,
    'unit_price': 51.329,
    'line_total': 51.33},
   {'description': 'BROWN 25 LB',
    'quantity': 1.0,
    'unit_price': 26.778,
    'line_total': 26.78},
   {'description': 'OAT 12 X 32 OZ',
    'quantity': 2.0,
    'unit_price': 39.948,
    'line_total': 79.9},
   {'description': 'LIQUID 2 X 20 LB',
    'quantity': 2.0,
    'unit_price': 100.35,
    'line_total': 200.7}]},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []},
 {'Invoice_Number': '',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '',
  'Order_Date': '',
  'Invoice_Total': 0.0,
  'items': []}]

In [28]:
import csv

invoice_rows = []
lineitem_rows = []

for inv in all_invoices:

    # skip empty invoices
    if not inv["Invoice_Number"]:
        continue

    invoice_rows.append({
        "Invoice_Number": inv["Invoice_Number"],
        "Invoice_Date": inv["Invoice_Date"],
        "Vendor_Name": inv["Vendor_Name"],
        "Ship_To": inv["Ship_To"],
        "Cust_Id": inv["Cust_Id"],
        "Order_Date": inv["Order_Date"],
        "Invoice_Total": inv["Invoice_Total"]
    })

    for item in inv["items"]:

        lineitem_rows.append({
            "Invoice_Number": inv["Invoice_Number"],
            "description": item["description"],
            "quantity": item["quantity"],
            "unit_price": item["unit_price"],
            "line_total": item["line_total"]
        })

In [29]:
invoice_rows

[{'Invoice_Number': '440912',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '05/12/2025',
  'Invoice_Total': 289.85},
 {'Invoice_Number': '446026',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '08/11/2025',
  'Invoice_Total': 432.62},
 {'Invoice_Number': '444038',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '07/07/2025',
  'Invoice_Total': 557.38},
 {'Invoice_Number': '444434',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '07/14/2025',
  'Invoice_Total': 522.75},
 {'Invoice_Number': '445630',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '08/04/2025',
  'Invoice_Total': 596.94},
 {'Invoice_Number': '442055',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '06/02/2025',
  'Invoice_Total': 491.83},
 {'Invoice_Number': '443328',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '06/23/2025',
  'Invoice_Total': 738.17},
 {'Invoice_Number': '442951',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '06/16/2025',
  'Invoice_Total': 385.06},
 {'Invoice_Number': '444831',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '07/21/2025',
  'Invoice_Total': 576.63},
 {'Invoice_Number': '445193',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '07/28/2025',
  'Invoice_Total': 754.89},
 {'Invoice_Number': '442055',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '06/02/2025',
  'Invoice_Total': 491.83},
 {'Invoice_Number': '441300',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '05/19/2025',
  'Invoice_Total': 357.8},
 {'Invoice_Number': '442484',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '06/09/2025',
  'Invoice_Total': 688.51},
 {'Invoice_Number': '442484',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '06/09/2025',
  'Invoice_Total': 688.51},
 {'Invoice_Number': '441766',
  'Invoice_Date': '',
  'Vendor_Name': 'Pacific Food Importers',
  'Ship_To': 'Seattle WA',
  'Cust_Id': '6775',
  'Order_Date': '05/27/2025',
  'Invoice_Total': 551.21}]

In [18]:
lineitem_rows

[{'Invoice_Number': '440912',
  'description': 'POWER 50 LB',
  'quantity': 10.0,
  'unit_price': 24.063,
  'line_total': 240.63},
 {'Invoice_Number': '440912',
  'description': 'NITRILE LARGE 10 x 100 s',
  'quantity': 1.0,
  'unit_price': 29.774,
  'line_total': 29.77},
 {'Invoice_Number': '446026',
  'description': 'POWER 50 LB',
  'quantity': 10.0,
  'unit_price': 24.063,
  'line_total': 240.63},
 {'Invoice_Number': '446026',
  'description': 'BARISTA BLEND 12 X 32',
  'quantity': 1.0,
  'unit_price': 41.139,
  'line_total': 41.14},
 {'Invoice_Number': '446026',
  'description': 'LIQUID 2 X 20 LB',
  'quantity': 1.0,
  'unit_price': 95.225,
  'line_total': 95.23},
 {'Invoice_Number': '446026',
  'description': 'CANS 24 X 11 OZ',
  'quantity': 2.0,
  'unit_price': 27.81,
  'line_total': 55.62},
 {'Invoice_Number': '444038',
  'description': 'POWER 50 LB',
  'quantity': 10.0,
  'unit_price': 24.063,
  'line_total': 240.63},
 {'Invoice_Number': '444038',
  'description': 'NITRILE XL 10 x 100 ct s',
  'quantity': 1.0,
  'unit_price': 35.383,
  'line_total': 35.38},
 {'Invoice_Number': '444038',
  'description': 'EXTRA 12 X 454 GRM',
  'quantity': 1.0,
  'unit_price': 57.776,
  'line_total': 57.78},
 {'Invoice_Number': '444038',
  'description': 'OAT 12 X 32 OZ',
  'quantity': 3.0,
  'unit_price': 39.948,
  'line_total': 119.84},
 {'Invoice_Number': '444038',
  'description': 'LIQUID 2 X 20 LB',
  'quantity': 1.0,
  'unit_price': 100.35,
  'line_total': 100.35},
 {'Invoice_Number': '444434',
  'description': 'POWER 50 LB',
  'quantity': 12.0,
  'unit_price': 24.063,
  'line_total': 288.76},
 {'Invoice_Number': '444434',
  'description': 'YELLOW FINE 25 LB',
  'quantity': 1.0,
  'unit_price': 25.101,
  'line_total': 25.1},
 {'Invoice_Number': '444434',
  'description': 'NITRILE MEDIUM 10 x 100 s',
  'quantity': 1.0,
  'unit_price': 29.783,
  'line_total': 29.78},
 {'Invoice_Number': '444434',
  'description': 'SEEDS WHITE+ 4 X 5 LB',
  'quantity': 1.0,
  'unit_price': 80.25,
  'line_total': 80.25},
 {'Invoice_Number': '444434',
  'description': 'SEED 4 X 5.5 LB',
  'quantity': 1.0,
  'unit_price': 96.0,
  'line_total': 96.0},
 {'Invoice_Number': '444434',
  'description': 'KOSHER COARSE 9 X 3 LB',
  'quantity': 1.0,
  'unit_price': 75.076,
  'line_total': 75.08},
 {'Invoice_Number': '444434',
  'description': 'LIQUID 2 X 20 LB',
  'quantity': 2.0,
  'unit_price': 95.225,
  'line_total': 95.23},
 {'Invoice_Number': '445630',
  'description': 'POWER 50 LB',
  'quantity': 8.0,
  'unit_price': 24.063,
  'line_total': 192.5},
 {'Invoice_Number': '445630',
  'description': 'SEEDS WHITE+ 4 X 5 LB',
  'quantity': 1.0,
  'unit_price': 80.25,
  'line_total': 80.25},
 {'Invoice_Number': '445630',
  'description': 'SLICED 6 #10',
  'quantity': 1.0,
  'unit_price': 51.329,
  'line_total': 51.33},
 {'Invoice_Number': '445630',
  'description': 'OAT 12 X 32 OZ',
  'quantity': 3.0,
  'unit_price': 39.948,
  'line_total': 119.84},
 {'Invoice_Number': '445630',
  'description': 'GRANULATED CANE 25 LB',
  'quantity': 1.0,
  'unit_price': 28.587,
  'line_total': 28.59},
 {'Invoice_Number': '445630',
  'description': 'LIQUID 2 X 20 LB',
  'quantity': 1.0,
  'unit_price': 95.225,
  'line_total': 95.23},
 {'Invoice_Number': '442055',
  'description': 'POWER 50 LB',
  'quantity': 8.0,
  'unit_price': 24.063,
  'line_total': 192.5},
 {'Invoice_Number': '442055',
  'description': 'A/P UNBLEACHED 50 LB',
  'quantity': 1.0,
  'unit_price': 21.582,
  'line_total': 21.58},
 {'Invoice_Number': '442055',
  'description': 'MEDIUM RYE 50 LB',
  'quantity': 1.0,
  'unit_price': 42.8,
  'line_total': 42.8},
 {'Invoice_Number': '442055',
  'description': 'YELLOW FINE*** 25 LB',
  'quantity': 1.0,
  'unit_price': 25.861,
  'line_total': 25.86},
 {'Invoice_Number': '442055',
  'description': 'FRESH + 20 X 16 OZ',
  'quantity': 1.0,
  'unit_price': 54.62,
  'line_total': 54.62},
 {'Invoice_Number': '442055',
  'description': 'KOSHER COARSE 9 X 3 LB',
  'quantity': 1.0,
  'unit_price': 71.658,
  'line_total': 71.66},
 {'Invoice_Number': '442055',
  'description': 'NITRILE LARGE 10 x 100 s',
  'quantity': 1.0,
  'unit_price': 29.774,
  'line_total': 29.77},
 {'Invoice_Number': '442055',
  'description': 'LIQUID 2 X 20 LB',
  'quantity': 1.0,
  'unit_price': 100.35,
  'line_total': 50.18},
 {'Invoice_Number': '442055',
  'description': 'INSTANT RED LBL SAF 20 X',
  'quantity': 1.0,
  'unit_price': 133.418,
  'line_total': 133.42},
 {'Invoice_Number': '443328',
  'description': 'POWER 50 LB',
  'quantity': 8.0,
  'unit_price': 24.063,
  'line_total': 192.5},
 {'Invoice_Number': '443328',
  'description': 'SPRAY PREMIUM 6 X 14 OZ',
  'quantity': 1.0,
  'unit_price': 34.038,
  'line_total': 34.04},
 {'Invoice_Number': '443328',
  'description': 'KOSHER COARSE 9 X 3 LB',
  'quantity': 1.0,
  'unit_price': 75.076,
  'line_total': 75.08},
 {'Invoice_Number': '443328',
  'description': 'MINCED 4 X 4.5 LB',
  'quantity': 1.0,
  'unit_price': 104.0,
  'line_total': 104.0},
 {'Invoice_Number': '443328',
  'description': 'MINCED 4 X 6 LB',
  'quantity': 1.0,
  'unit_price': 112.0,
  'line_total': 112.0},
 {'Invoice_Number': '443328',
  'description': 'SEEDS WHITE+ 4 X 5 LB',
  'quantity': 1.0,
  'unit_price': 80.25,
  'line_total': 80.25},
 {'Invoice_Number': '443328',
  'description': 'OAT 12 X 32 OZ',
  'quantity': 1.0,
  'unit_price': 39.948,
  'line_total': 39.95},
 {'Invoice_Number': '443328',
  'description': 'LIQUID 2 X 20 LB',
  'quantity': 1.0,
  'unit_price': 100.35,
  'line_total': 100.35},
 {'Invoice_Number': '443328',
  'description': 'BARISTA BLEND 12 X 32',
  'quantity': 1.0,
  'unit_price': 41.139,
  'line_total': 41.14},
 {'Invoice_Number': '442951',
  'description': 'POWER 50 LB',
  'quantity': 10.0,
  'unit_price': 24.063,
  'line_total': 240.63},
 {'Invoice_Number': '442951',
  'description': 'LIQUID 2 X 20 LB',
  'quantity': 1.0,
  'unit_price': 100.35,
  'line_total': 100.35},
 {'Invoice_Number': '442951',
  'description': 'NITRILE XL 10 x 100 ct s',
  'quantity': 1.0,
  'unit_price': 35.361,
  'line_total': 35.36},
 {'Invoice_Number': '444831',
  'description': 'POWER 50 LB',
  'quantity': 10.0,
  'unit_price': 24.063,
  'line_total': 240.63},
 {'Invoice_Number': '444831',
  'description': 'POWDER DIASTATIC+ 50 LB',
  'quantity': 1.0,
  'unit_price': 116.848,
  'line_total': 116.85},
 {'Invoice_Number': '444831',
  'description': 'SLICED 6 #10',
  'quantity': 1.0,
  'unit_price': 51.329,
  'line_total': 51.33},
 {'Invoice_Number': '444831',
  'description': 'NITRILE MEDIUM 10 x 100 s',
  'quantity': 1.0,
  'unit_price': 29.78,
  'line_total': 29.78},
 {'Invoice_Number': '444831',
  'description': 'LIQUID 2 X 20 LB',
  'quantity': 1.0,
  'unit_price': 95.225,
  'line_total': 95.23},
 {'Invoice_Number': '444831',
  'description': 'OAT 12 X 32 OZ',
  'quantity': 1.0,
  'unit_price': 39.948,
  'line_total': 39.95},
 {'Invoice_Number': '445193',
  'description': 'POWER 50 LB',
  'quantity': 10.0,
  'unit_price': 24.063,
  'line_total': 240.63},
 {'Invoice_Number': '445193',
  'description': 'MINCED 4 X 4.5 LB',
  'quantity': 1.0,
  'unit_price': 113.333,
  'line_total': 113.33},
 {'Invoice_Number': '445193',
  'description': 'SEEDS WHITE+ 4 X 5 LB',
  'quantity': 1.0,
  'unit_price': 80.25,
  'line_total': 80.25},
 {'Invoice_Number': '445193',
  'description': 'KOSHER COARSE 9 X 3 LB',
  'quantity': 2.0,
  'unit_price': 75.076,
  'line_total': 150.15},
 {'Invoice_Number': '445193',
  'description': 'NITRILE XL 10 x 100 ct s',
  'quantity': 1.0,
  'unit_price': 36.25,
  'line_total': 36.25},
 {'Invoice_Number': '445193',
  'description': 'INSTANT RED LBL SAF 20 X',
  'quantity': 1.0,
  'unit_price': 130.797,
  'line_total': 130.8},
 {'Invoice_Number': '442055',
  'description': 'POWER 50 LB',
  'quantity': 8.0,
  'unit_price': 24.063,
  'line_total': 192.5},
 {'Invoice_Number': '442055',
  'description': 'A/P UNBLEACHED 50 LB',
  'quantity': 1.0,
  'unit_price': 21.582,
  'line_total': 21.58},
 {'Invoice_Number': '442055',
  'description': 'MEDIUM RYE 50 LB',
  'quantity': 1.0,
  'unit_price': 42.8,
  'line_total': 42.8},
 {'Invoice_Number': '442055',
  'description': 'YELLOW FINE*** 25 LB',
  'quantity': 1.0,
  'unit_price': 25.861,
  'line_total': 25.86},
 {'Invoice_Number': '442055',
  'description': 'FRESH + 20 X 16 OZ',
  'quantity': 1.0,
  'unit_price': 54.62,
  'line_total': 54.62},
 {'Invoice_Number': '442055',
  'description': 'KOSHER COARSE 9 X 3 LB',
  'quantity': 1.0,
  'unit_price': 71.658,
  'line_total': 71.66},
 {'Invoice_Number': '442055',
  'description': 'NITRILE LARGE 10 x 100 s',
  'quantity': 1.0,
  'unit_price': 29.774,
  'line_total': 29.77},
 {'Invoice_Number': '442055',
  'description': 'LIQUID 2 X 20 LB',
  'quantity': 1.0,
  'unit_price': 100.35,
  'line_total': 50.18},
 {'Invoice_Number': '442055',
  'description': 'INSTANT RED LBL SAF 20 X',
  'quantity': 1.0,
  'unit_price': 133.418,
  'line_total': 133.42},
 {'Invoice_Number': '441300',
  'description': 'POWER 50 LB',
  'quantity': 8.0,
  'unit_price': 24.063,
  'line_total': 192.5},
 {'Invoice_Number': '441300',
  'description': 'SEEDS WHITE+ 4 X 5 LB',
  'quantity': 1.0,
  'unit_price': 80.25,
  'line_total': 80.25},
 {'Invoice_Number': '441300',
  'description': 'WHOLE GALLON RED CAP 4',
  'quantity': 1.0,
  'unit_price': 17.999,
  'line_total': 18.0},
 {'Invoice_Number': '441300',
  'description': 'GRANULATED CANE 25 LB',
  'quantity': 1.0,
  'unit_price': 29.147,
  'line_total': 29.15},
 {'Invoice_Number': '441300',
  'description': 'NITRILE MEDIUM 10 x 100 s',
  'quantity': 1.0,
  'unit_price': 29.771,
  'line_total': 29.77},
 {'Invoice_Number': '442484',
  'description': 'POWER 50 LB',
  'quantity': 12.0,
  'unit_price': 24.063,
  'line_total': 288.76},
 {'Invoice_Number': '442484',
  'description': 'POWDER DIASTATIC+ 50 LB',
  'quantity': 1.0,
  'unit_price': 119.177,
  'line_total': 119.18},
 {'Invoice_Number': '442484',
  'description': 'SLICED 6 #10',
  'quantity': 1.0,
  'unit_price': 51.329,
  'line_total': 51.33},
 {'Invoice_Number': '442484',
  'description': 'OAT 12 X 32 OZ',
  'quantity': 3.0,
  'unit_price': 39.948,
  'line_total': 119.84},
 {'Invoice_Number': '442484',
  'description': 'SEEDS WHITE+ 4 X 5 LB',
  'quantity': 1.0,
  'unit_price': 80.25,
  'line_total': 80.25},
 {'Invoice_Number': '442484',
  'description': 'GRANULATED CANE 25 LB',
  'quantity': 1.0,
  'unit_price': 29.147,
  'line_total': 29.15},
 {'Invoice_Number': '442484',
  'description': 'INSTANT RED LBL SAF 20 X',
  'quantity': -1.0,
  'unit_price': 133.418,
  'line_total': -133.42},
 {'Invoice_Number': '442484',
  'description': 'FRESH + 20 X 16 OZ',
  'quantity': -1.0,
  'unit_price': 54.62,
  'line_total': -54.62},
 {'Invoice_Number': '442484',
  'description': 'POWER 50 LB',
  'quantity': 12.0,
  'unit_price': 24.063,
  'line_total': 288.76},
 {'Invoice_Number': '442484',
  'description': 'POWDER DIASTATIC+ 50 LB',
  'quantity': 1.0,
  'unit_price': 119.177,
  'line_total': 119.18},
 {'Invoice_Number': '442484',
  'description': 'SLICED 6 #10',
  'quantity': 1.0,
  'unit_price': 51.329,
  'line_total': 51.33},
 {'Invoice_Number': '442484',
  'description': 'OAT 12 X 32 OZ',
  'quantity': 3.0,
  'unit_price': 39.948,
  'line_total': 119.84},
 {'Invoice_Number': '442484',
  'description': 'SEEDS WHITE+ 4 X 5 LB',
  'quantity': 1.0,
  'unit_price': 80.25,
  'line_total': 80.25},
 {'Invoice_Number': '442484',
  'description': 'GRANULATED CANE 25 LB',
  'quantity': 1.0,
  'unit_price': 29.147,
  'line_total': 29.15},
 {'Invoice_Number': '442484',
  'description': 'INSTANT RED LBL SAF 20 X',
  'quantity': -1.0,
  'unit_price': 133.418,
  'line_total': -133.42},
 {'Invoice_Number': '442484',
  'description': 'FRESH + 20 X 16 OZ',
  'quantity': -1.0,
  'unit_price': 54.62,
  'line_total': -54.62},
 {'Invoice_Number': '441766',
  'description': 'POWER 50 LB',
  'quantity': 8.0,
  'unit_price': 24.063,
  'line_total': 192.5},
 {'Invoice_Number': '441766',
  'description': 'SLICED 6 #10',
  'quantity': 1.0,
  'unit_price': 51.329,
  'line_total': 51.33},
 {'Invoice_Number': '441766',
  'description': 'BROWN 25 LB',
  'quantity': 1.0,
  'unit_price': 26.778,
  'line_total': 26.78},
 {'Invoice_Number': '441766',
  'description': 'OAT 12 X 32 OZ',
  'quantity': 2.0,
  'unit_price': 39.948,
  'line_total': 79.9},
 {'Invoice_Number': '441766',
  'description': 'LIQUID 2 X 20 LB',
  'quantity': 2.0,
  'unit_price': 100.35,
  'line_total': 200.7}]

In [25]:
import pandas as pd

invoice_df = pd.DataFrame(invoice_rows)

In [26]:
line_items_df = pd.DataFrame(lineitem_rows)

In [30]:
with open("invoices.csv", "w", newline="") as f:

    writer = csv.DictWriter(
        f,
        fieldnames=[
            "Invoice_Number",
            "Invoice_Date",
            "Vendor_Name",
            "Ship_To",
            "Cust_Id",
            "Order_Date",
            "Invoice_Total"
        ]
    )

    writer.writeheader()
    writer.writerows(invoice_rows)

print("invoices.csv saved successfully")

invoices.csv saved successfully

In [31]:
with open("lineitems.csv", "w", newline="") as f:

    writer = csv.DictWriter(
        f,
        fieldnames=[
            "Invoice_Number",
            "description",
            "quantity",
            "unit_price",
            "line_total"
        ]
    )

    writer.writeheader()
    writer.writerows(lineitem_rows)

print("lineitems.csv saved successfully")

lineitems.csv saved successfully

In [32]:
invoices = pd.read_csv("/content/invoices.csv")
invoices

,Invoice_Number,Invoice_Date,Vendor_Name,Ship_To,Cust_Id,Order_Date,Invoice_Total
0,440912,NaN,Pacific Food Importers,Seattle WA,6775,05/12/2025,289.85
1,446026,NaN,Pacific Food Importers,Seattle WA,6775,08/11/2025,432.62
2,444038,NaN,Pacific Food Importers,Seattle WA,6775,07/07/2025,557.38
3,444434,NaN,Pacific Food Importers,Seattle WA,6775,07/14/2025,522.75
4,445630,NaN,Pacific Food Importers,Seattle WA,6775,08/04/2025,596.94
5,442055,NaN,Pacific Food Importers,Seattle WA,6775,06/02/2025,491.83
6,443328,NaN,Pacific Food Importers,Seattle WA,6775,06/23/2025,738.17
7,442951,NaN,Pacific Food Importers,Seattle WA,6775,06/16/2025,385.06
8,444831,NaN,Pacific Food Importers,Seattle WA,6775,07/21/2025,576.63
9,445193,NaN,Pacific Food Importers,Seattle WA,6775,07/28/2025,754.89
10,442055,NaN,Pacific Food Importers,Seattle WA,6775,06/02/2025,491.83
11,441300,NaN,Pacific Food Importers,Seattle WA,6775,05/19/2025,357.80
12,442484,NaN,Pacific Food Importers,Seattle WA,6775,06/09/2025,688.51
13,442484,NaN,Pacific Food Importers,Seattle WA,6775,06/09/2025,688.51
14,441766,NaN,Pacific Food Importers,Seattle WA,6775,05/27/2025,551.21

In [33]:
lineItems = pd.read_csv("/content/lineitems.csv")
lineItems

    Invoice_Number               description  quantity  unit_price  line_total
0           440912               POWER 50 LB      10.0      24.063      240.63
1           440912  NITRILE LARGE 10 x 100 s       1.0      29.774       29.77
2           446026               POWER 50 LB      10.0      24.063      240.63
3           446026     BARISTA BLEND 12 X 32       1.0      41.139       41.14
4           446026          LIQUID 2 X 20 LB       1.0      95.225       95.23
..             ...                       ...       ...         ...         ...
87          441766               POWER 50 LB       8.0      24.063      192.50
88          441766              SLICED 6 #10       1.0      51.329       51.33
89          441766               BROWN 25 LB       1.0      26.778       26.78
90          441766            OAT 12 X 32 OZ       2.0      39.948       79.90
91          441766          LIQUID 2 X 20 LB       2.0     100.350      200.70

[92 rows x 5 columns]